.meteor/packages

Solution: add meteor session package

Problem: no client side persistent storage

---

.meteor/packages
.meteor/versions
client/addCoin.js
client/menu.js
lib/database/FormData.js
lib/routes.js
views/layouts/root.html
views/templates/addCoin.html

Solution: add numerous options to the add coin form to allow for most foreseeable blockchain situations.

Problem: add coin form not comprehensive

---

client/addCoin.js

Solution: add more JS logic for form elements, fix some broken logic so that all details are passed to the database. Also kindly ask the router to send us back to root page after successful form submission.

Problem: Form not working properly

---

.meteor/packages
client/addCoin.js
views/templates/addCoin.html
views/templates/formHelp/addCoin.html

Solution: add logic and text so that hints show directly below each form element when selected

Problem: no guidance when filling out form

---

README.md

Solution: update build instructions to install npm modules automatically.

Problem: build instructions do not include npm

---

client/users/addCoin.js
lib/database/Currencies.js
server/serverdb/addCoin.js
views/templates/users/addCoin.html

Solution: add items as well as logic and database stuff

Problem: items missing from new currency form

---

client/users/activityLog.js
lib/database/ActivityLog.js
lib/database/Currencies.js
views/templates/users/activityLog.html

Solution: change activitylog database schema so that sorting is trivial

Problem: message system does not allow sorting messages in reverse order

---

.meteor/packages
.meteor/versions
client/users/wallet.js
lib/database/ActivityLog.js
lib/database/Wallet.js
lib/routes.js
server/main.js
server/serverdb/UserData.js
views/templates/normal/menu.html
views/templates/users/wallet.html

Solution: add basic wallet page showing balance and transaction history

Problem: user cannot see their wallet balance or transactions history

---

client/moderators/moderatorPendingCurrency.js
lib/database/Currencies.js
server/serverdb/rewards.js
views/templates/users/wallet.html

Solution: add logic to credit users wallets with coins when a moderator approves their currency.

Problem: users wallets are not credited with coins when currency approved

---

client/normal/currency.css
client/normal/currency.js
client/normal/currencyDetail.js
client/normal/currencyDetail/fundamentalMetrics.js
client/normal/returnedCurrencies.js
lib/routes.js
server/main.js
views/templates/normal/bounties.html
views/templates/normal/currency.html
views/templates/normal/currencyDetail.html
views/templates/normal/menu.html
views/templates/users/edit.html

Solution: add a page that shows the details of the current currency (more than the front page where space is limited).

Problem: no currency detail page for more information

---

client/normal/bounties/bounties.js
client/normal/currency.css
lib/routes.js
views/templates/normal/bounties.html

Solution: add bounty page layout and sample data

Problem: bounty page is blank

---

.meteor/packages
.meteor/versions
client/moderators/moderatorDash.js
client/moderators/moderatorPendingCurrency.js
client/normal/bounties/bounties.js
client/normal/bounties/rainbow.js
client/users/userPendingCurrencies.js
lib/database/ActivityLog.js
lib/database/Bounties.js
lib/database/Currencies.js
lib/routes.js
server/API_requests/github.js
server/main.js
server/serverdb/APICalls.js
server/serverdb/addCoin.js
server/serverdb/rewards.js
views/layouts/desktop.html
views/layouts/editAnything.html
views/layouts/root.html
views/templates/moderators/moderatorDash.html
views/templates/moderators/moderatorPendingCurrency.html
views/templates/normal/bounties.html
views/templates/users/userPendingCurrencies.html

Solution: Build out the bounty system, API fetching system, and HashrateAPI bounty object.

Problem: users cannot add API calls to fetch hashrate

---

.meteor/packages
.meteor/versions
client/normal/bounties/bounties.js
client/normal/currency.css
client/normal/currencyDetail/fundamentalMetrics.js
lib/database/Features.js
views/layouts/root.html
views/templates/normal/currencyDetail/currencyDetail.html
views/templates/normal/currencyDetail/features.html

Solution: allow users to add features for any currency

Problem: features section doesn't allow user content

---

client/normal/currencyDetail/fundamentalMetrics.js
lib/database/Features.js
views/templates/normal/currencyDetail/features.html

Solution: add basic flagging and voting.

Problem: no spam filtering or voting on comments

---

client/normal/currencyDetail/fundamentalMetrics.js
lib/database/Features.js
views/templates/normal/currencyDetail/features.html

Features and comments are not being sorted, cant rate comments, features dont show total number of comments, etc.
Solution: a few small fixes for to make the features and comments section work properly

Problem: features and comments not working properly

---

client/users/ratings/ratings.js
lib/database/Ratings.js
server/methods/imageUpload.js
views/templates/users/ratings.html

solution: add framework for users to answer rating quesions

problem: users cannot answer rating questions

---

client/moderators/moderatorDash.js
client/users/ratings/ratings.js
server/libs/index.js
server/methods/imageUpload.js
views/templates/moderators/approveWalletImage.html
views/templates/moderators/moderatorDash.html
views/templates/users/ratings.html

Problem: various issues with rating system

---

server/methods/imageUpload.js
views/layouts/root.html
views/templates/moderators/approveWalletImage.html

solution: update image dir so that it uses the nginx dir on server

problem:wallet image dir doesnt work on server

---

.meteor/packages
.meteor/versions

Solution: add facebook and github frameworks
Partial solution to #39

Problem: no community login options

---

client/normal/currency.js
client/users/ratings/ratings.js
lib/database/GraphData.js
server/methods/elorankings.js
views/templates/users/ratings.html

Just a quick PR to send recent fixes for a variety of ELO ranking problems before other people start working on the project.

Problem: multiple issues with ELO ranking

---

.gitignore
client/moderators/moderatorDash.js
client/normal/currency.js
client/normal/currencyDetail.js
client/normal/returnedCurrencies.js
client/users/activityLog.js
client/users/ratings/ratings.js
client/users/userPendingCurrencies.js
client/users/wallet.js

https://github.com/Blockrazor/blockrazor/issues/34
Solution: Bind autorun to template instances and declare subscription.
FlowRouter route to addcoin involves subscription that I'm unsure that it requires change.
Changed ratings.js readiness callback.

Problem: mongo subscriptions don't start and end correctly

---

README.md

solution: add paid contributor info

problem: readme doesnt have paid contributor info

---

.meteor/packages

solution: force removal of Semantic-UI packages

problem: semantic-UI still messing around with things

---

README.md

solution: add command to restore example database

problem: readme does not include database restore

---

AUTHORS
client/normal/currencyDetail.js
lib/database/Currencies.js

solution: only publish/subscribe to data for the current currency when in a currency detail page

problem: currency detail page subscribes to all currency and comment data #50

---

README.md

solution: emolden the part about commenting on an issue you want to work on

problem: multiple people working on same issue

---

client/users/ratings/ratings.js
lib/properties.js
package-lock.json
package.json
server/methods/imageUpload.js

solution: Implement local client validation to prevent large files being uploaded and none image file types. Server side validation also implemented within the method for further security. Issue #6.

problem: wallet images uploads file type and file size are not validated

---

client/normal/menu.js
client/users/activityLog.js
server/methods/notifications.js
views/templates/normal/menu.html

solution: A bootstrap badge is now visible in the menu showing how many notifications which have not been read. Opening the notification view will mark all notification as read:true.

problem: Users are not able to see if they have notifications easily #45

---

.meteor/packages
.meteor/versions
server/main.js

solution: implemented ostrio/logger and logging login events at present. More to follow once defined

problem: no solution exists to log events #48

---

server/main.js

solution: remove offending code. Accounts service configuration set directly in database as credentials should not be stored in public source files

problem: #44 breaks accounts service configuration

---

client/main.js
client/normal/menu.js
views/templates/normal/menu.html

solution: add the client onLogin hook on the client and call the notificationCount method. This resolve all above issues #85

problem: Notification bubble is not refreshed on login or logout #85

---

client/main.css
client/main.js
client/normal/returnedCurrencies.js
views/templates/normal/returnedCurrencies.html

solution: Add basic filtering to filter currencies reactively. I have no added all attributes until we defined what attributes need filtering on. Also some attribues will rely on ui elelements. e.g. date/time lookups.

problem: No ability to filter currencies

---

client/main.js

performing conflict resolution on #95 due to commit pushed on outdated codebase broke something
solution: fix code by adding closing parens

problem: app cant start due to missing parens

---

README.md

Sometimes contributors create changes on top of a previous version which causes problems with conflicts when trying to merge.
solution: add pop and stash routine to make sure commits are based on latest version of any given file.

problem: contributors are sometimes running into PR conflicts

---

client/users/ratings/ratings.js

solution: remove fetch and refactor code to use .count()

problem: fetch is used instead of .count() #67

---

lib/database/ActivityLog.js
lib/database/Bounties.js
lib/database/Currencies.js
lib/database/Features.js
lib/database/Ratings.js
lib/database/Wallet.js
server/methods/imageUpload.js
server/serverdb/UserData.js

solution: replace with this.userId #99

problem:Meteor.user() is used on the server which invokes a DB connection

---

lib/properties.js

solution: use production directory

problem: incorrect wallet upload directory

---

client/main.js
client/moderators/moderatorDash.js
client/moderators/moderatorPendingCurrency.js
client/normal/bounties/bounties.js
client/normal/currencyDetail/fundamentalMetrics.js
client/normal/menu.js
client/normal/returnedCurrencies.js
client/users/addCoin.js
views/templates/moderators/moderatorDash.html
views/templates/normal/bounties.html
views/templates/normal/currencyDetail/features.html
views/templates/users/addCoin.html
views/templates/users/userPendingCurrencies.html

solution: Replace Session with ReactiveVar (and ReactiveDict) everywhere to prevent pollution of the global scope

problem: Session is global and should be avoided

---

client/normal/currencyDetail/fundamentalMetrics.js
views/templates/normal/currencyDetail/currencyDetail.html

Solution: Allow users to compare multiple currencies on the radar chart

Problem: Users cannot directly compare currencies (issue #51)

---

client/main.js
client/users/addCoin.js
lib/properties.js
server/serverdb/addCoin.js
views/templates/users/addCoin.html

solution: added ability to upload images when adding a coin #27

problem: currencies do not have logos

---

.meteor/packages
.meteor/versions
client/normal/currency.js
client/normal/currencyDetail.js
client/normal/currencyDetail/fundamentalMetrics.js
lib/database/Currencies.js
lib/routes.js

Solution: Use a slug (URL friendly string) generated from currency name instead of currency _id in the URL

Problem: Currency details page uses currency _id in url (issue #114)

---

AUTHORS
lib/database/AppLogs.js
server/connections.js
server/main.js

solution: log users IP address on login and creation, raise warnings if certain rules are met

problem: users can create multiple accounts

---

client/users/ratings/ratings.js
lib/database/Ratings.js
views/templates/users/ratings.html

Problem: Confusing response if a user tries to add wallet pictures for a currency that they've already previously added images for (issue #31)
Solution: Add a list of currencies that this user has already added/rated to the top of the page and let them know they can add more if they want

Problem: Confusing response if a user tries to add wallet pictures

---

client/users/ratings/ratings.js
views/templates/users/ratings.html

Solution: Add a way to filter cryptocurrencies by name and by symbol

Problem: No filter on ratings page (issue #120)

---

client/normal/login.js
client/normal/menu.js
client/normal/signup.js
lib/routes.js
views/templates/normal/login.html
views/templates/normal/menu.html
views/templates/normal/signup.html

Solution: Add a new login and signup page

Problem: No login/signup page (issue #123)

---

lib/routes.js

Solution: If the user is not logged in, redirect him to /login, otherwise render /addcoin

Problem: No redirection to the login page on /addcoin (issue #123)

---

client/normal/currencyDetail/redFlagCurrency.js
lib/database/Redflags.js
views/templates/normal/currencyDetail/currencyDetail.html
views/templates/normal/currencyDetail/redflags.html

solution: add UI to add red flags and comment on them per the same requirement as features

problem: users cannot add red flags to currencies #55

---

server/methods/elorankings.js
server/methods/imageUpload.js

Solution: Add a way to mark questions as negative and inverse ELO accordingly

Problem: Cannot use inverse ELO rating for comparison questions (#29)

---

client/users/addCoin.js

Solution: Report the error back to the user with explanation how to fix it.

Problem: No error handling on /addcoin (#132)

---

lib/database/Bounties.js
server/API_requests/github.js
server/main.js
server/methods/communityrank.js
server/methods/elorankings.js
server/methods/imageUpload.js
server/methods/notifications.js
server/serverdb/addCoin.js

Solution: Use the already implemented ostrio:logger to log all server errors

Problem: Server errors are not logged (#135)

---

.meteor/packages

solution: removed meteor jquery package as its already included in root.html should not include twice

problem: modals are broken

---

lib/api.js
lib/database/Bounties.js
lib/database/Currencies.js
lib/database/UserData.js
server/serverdb/rewards.js
views/templates/normal/menu.html

solution: create a helper and simple api to reference a new helper called isModerator, can be called in any template.

problem: UserData collection is only exported on the server #134

---

client/moderators/questions.js
server/methods/imageUpload.js
views/templates/moderators/questions.html

Solution: Add new UI for questions where you can easily mark them as negative and manage them

Problem: Cannot easily flag questions with negative meaning (#29)

---

server/methods/elorankings.js

problem: 
```
log.error('Error in tabulateElo.', err)
```
causes error.
solution: comment out offending line.
notify: @anbud

problem: #135 breaks method

---

server/methods/imageUpload.js

#135 breaks image upload
solution: dont use error.log
notify @anbud

problem: image watermarking broken

---

lib/properties.js

solution: update coin image public location
Loosely related to #143

problem: coin images not displayed

---

client/main.js
client/normal/currency.js
client/normal/returnedCurrencies.js
lib/api.js

solution: use template level Template.instance().subscriptionsReady() to only run code when the subscription is ready and returned data

problem:radar chart tries to render before subscription is ready #93

---

.meteor/packages
client/users/profile.js
lib/api.js
lib/database/UserData.js
lib/routes.js
server/main.js
server/methods/profile.js
views/templates/normal/menu.html
views/templates/users/profile.html

problem: Not possible to update email, username in user profile & no github username in Meteor.user() object #44 #154
solution: add github username in OnCreateUser Hook & profile page to edit username and email

problem: not possible to update email,username in user profile #44 #154

---

AUTHORS
server/serverdb/addCoin.js

solution: merge multiple loops into one loop with different branches

problem: fix multiple loops over the same collection

---

server/methods/elorankings.js

Solution: Ignore any ties in elo ranking

Problem: Elo ranking does weird stuff when tie (#144)

---

server/serverdb/addCoin.js

sometimes multiple tags must be selected (for example an altcoin could also be a proposal). This doesn't work due to else if iteration.
Reference #157 + #158

problem: multiple tags not selected

---

client/normal/currency.js
client/normal/currencyDetail/fundamentalMetrics.js
client/users/codebase.js
client/users/developers.js
lib/api.js
lib/database/Codebase.js
lib/database/Developers.js
lib/database/UserData.js
lib/routes.js
server/methods/codebaserank.js
server/methods/elorankings.js
views/templates/normal/menu.html
views/templates/users/codebase.html
views/templates/users/developers.html

Solution: Add a codebase ranking system

Problem: Users can't rate the codebase of a currency (#54)

---

DESCRIPTIVE_C4.MD

Solution: Mention Hintjens and licensing at the top, and refer to the
full book.

Problem: Descriptive C4 carries no attribution

---

imports/startup/client/index.js
imports/startup/client/routes.js

solution: create new file structure in preparation for code refactor #69

problem:new file structure does not exist

---

client/users/codebase.js
client/users/communities.js
client/users/ratings/ratings.js
server/methods/elorankings.js

Solution: Separate graphdata population from averageElo method into a separate method

Problem: Graphdata is being populated incorrectly (#159)

---

client/moderators/questions.js
client/users/decentralization.js
lib/routes.js
server/methods/decentralization.js
server/methods/elorankings.js
server/methods/imageUpload.js
views/templates/moderators/questions.html
views/templates/normal/menu.html
views/templates/users/decentralization.html

Solution: Add a way to measure decentralization

Problem: Level of decentralization is not measured (#160)

---

client/users/decentralization.js
server/methods/decentralization.js

Solution: Use the correct method names, change Rating to Ranking

Problem: Wrong method names called for decentralization metrics (#160)

---

lib/database/UserData.js
server/main.js

Solution: Check if the mail is already in use when registering, and flag users that access the site using the same IP address

Problem: Users can create multiple accounts (#39)

---

imports/api/coins/methods.js
imports/ui/pages/changedCurrencies/changedCurrencies.html
imports/ui/pages/changedCurrencies/changedCurrencies.js
imports/ui/pages/currencyEdit/currencyEdit.js
lib/properties.js

solution: New feature to vote on changes and when votes reach >=3 the change is merged into currencies collection #164

problem: unable to merge proposed changes into currencies collection

---

client/normal/currencyDetail.js
views/templates/normal/currencyDetail/currencyDetail.html

Solution: added bare attributes to view, more attributs to come. Can be styled better when theme/UX is done, happy to change it more now though based on feedback

problem: currency detail page does not show many details #169

---

client/normal/currencyDetail.js
views/templates/normal/currencyDetail/currencyDetail.html

solution: add truncate helper to limit text

problem: long URL was skewing page

---

imports/api/hashpower/methods.js
imports/ui/pages/hashpower/addHashpower.js
imports/ui/pages/hashpower/addHashpower.template.html
imports/ui/pages/hashpower/allHashpower.js
imports/ui/pages/hashpower/allHashpower.template.html
lib/database/HashUnits.js
package-lock.json
package.json

Solution: Allow users to select a unit from already added units or add new units

Problem: Adding hashpower device has fixed options for unit (#179)

---

client/normal/currencyDetail.js
imports/startup/client/routes.js
imports/ui/pages/currencyEdit/currencyEdit.js
views/templates/normal/currencyDetail/currencyDetail.html

…n confusing
solution: add currency logo, and when editing a field highlight field red, auto focus and scroll to #186 183

problem: curreyncy logo not on detail and edit a currency confusing 

---

server/methods/elorankings.js

Solution: Add default values to solve edge cases in code (i.e. when data is missing)

Problem: Something weird happening with graphdata collection (#187)

---

client/normal/currencyDetail/fundamentalMetrics.js
lib/database/Features.js
lib/database/Images.js
server/methods/imageUpload.js

Solution: Subscribe to Features and WalletImages by slug instead by _id to improve performance and potentially fix the flashing problem

Problem: Currency detail page 'flashes' on load (#190)

---

client/users/addCoin.js
client/users/ratings/ratings.js

solution: use mimetype library on client instead of grabbing file extension #184

problem: wrong extension is being saved on client

---

server/methods/imageUpload.js

solution: Remove original file and only keep the watermarked image, rename watermarked image to just md5.png #200

problem:non-watermarked image used for wallet image display

---

.meteor/packages
client/normal/bounties/bounties.js
client/users/addCoin.js
lib/database/Bounties.js
lib/database/Currencies.js
server/serverdb/addCoin.js
server/serverdb/rewards.js
views/templates/users/addCoin.html

Solution: Add the 'add currency' bounty to the bounty list, algorithmically calculate the reward based on the time passed and modify the bounty system to work with 'add currency' bounties

Problem: Bounty page does not encourage users to add new currencies(#198)

---

server/methods/imageUpload.js

solution: modify GD function to not scale the image resolution up and leave as is

problem: file size of watermarked images is too high #199

---

client/normal/bounties/bounties.js
client/users/addCoin.js
lib/database/Bounties.js
views/templates/normal/bounties.html

Solution: Cancel the 'add currency' bounty when the user clicks on the cancel button both on the bounties page and on the addCoin page

Problem: Bounty timer is not reset when cancelled (#205)

---

client/moderators/questions.js
server/methods/imageUpload.js

solution: check if user is moderator and if so allow them to modify questions

problem: moderators cannot edit questions

---

server/API_requests/github.js
server/serverdb/addCoin.js

Solution: Automagically generate GitHub API request URL from the GitHub repo when currency is created

Problem: GitHub API request not automagically generated (#215)

---

imports/api/coins/methods.js
imports/ui/pages/changedCurrencies/changedCurrencies.html
imports/ui/pages/changedCurrencies/changedCurrencies.js
imports/ui/pages/currencyEdit/currencyEdit.js
imports/ui/pages/hashpower/allHashpower.template.html
views/templates/normal/menu.html

solution: Implemented new downvote button and logic handling #212

problem: Unable to downvote proposed changes

---

imports/api/coins/methods.js
imports/ui/pages/changedCurrencies/changedCurrencies.js
lib/database/Currencies.js

solution: Find uses a cursor and was causing an issue, changed to findOne #212

problem: moderator security had a minor bug with voting

---

lib/database/Currencies.js

solution: Adjust publication to only subscribe on currencies where status !=merged #217

problem: merged currencies are still visible in changeCurrencies view

---

client/normal/currencyDetail.js

solution: check if val is set and === 0 instead of just checking if its fasly #213

problem: issues when premine is legit 0

---

client/users/addCoin.js
lib/database/Ratings.js
server/serverdb/addCoin.js
views/templates/moderators/questions.html
views/templates/users/addCoin.html

Solution: Implement a way to add nominal questions to the 'add currency' page, save the results in the Currencies collection and update the ELO rating accordingly

Problem: Decentralization measurements are nominal not comparative(#219)

---

client/normal/currency.js
client/normal/currencyDetail/fundamentalMetrics.js

Solution: Display decentralization metric data on radar charts on the home page and on the currency page

Problem: Decentralization metric not displayed (#209)

---

imports/api/coins/methods.js
imports/ui/pages/changedCurrencies/changedCurrencies.js
lib/database/Currencies.js
lib/properties.js

solution: Proposed coin changes are now deleted when exceeding defined threshold in properties.js #234

problem: proposed coin changes are not deleted when downvote > _param

---

client/normal/currency.js
client/normal/currencyDetail/fundamentalMetrics.js
server/methods/elorankings.js

Solution: Calculate min and max values for ongoing development when updating graph data and display the appropriate values

Problem: Ongoing development metric not calculated or used (#238)

---

imports/api/coins/methods.js

solution: update method to remove [ ] as this value does not need evaluation #230

problem: when coins are merged they are saved as arrays

---

client/normal/currency.css
views/templates/normal/currencyDetail/features.html
views/templates/normal/currencyDetail/redflags.html

**Problem**: comments on the currency detail page don't look very good
**Solution** : Add custom css and changes in features.html , redflags.html inner templates.

Problem: comments on the currency detail page don't look very good #224"

---

client/moderators/questions.js
client/users/codebase.js
client/users/communities.js
client/users/ratings/ratings.js
server/methods/codebaserank.js
server/methods/communityrank.js
server/methods/imageUpload.js
views/templates/moderators/questions.html

Solution: Implement XOR questions to check for contradictory answers and prevent a high number of ties

Problem: Very easy to cheat on comparative ranking (#244)

---

client/normal/bounties/bounties.js
client/normal/currencyDetail/fundamentalMetrics.js
client/users/addCoin.js

solution: remove jquery cookie from compatibility directory and use NPM. #259

problem: modals were not loading due to depency issue

---

client/users/ratings/ratings.js
views/templates/normal/currencyDetail/currencyDetail.html
views/templates/users/ratings.html

solution: created new helper to show images #267

problem: coin images not showing up in questions on rating

---

client/normal/bounties/bounties.js
client/users/addCoin.js
client/users/codebase.js
client/users/communities.js
client/users/ratings/ratings.js
imports/api/hashpower/methods.js
imports/api/server/bounties.js
imports/startup/server/index.js
imports/ui/pages/hashpower/addHashpower.js
lib/database/Bounties.js
lib/database/Currencies.js
server/main.js
server/methods/codebaserank.js
server/methods/communityrank.js
server/methods/imageUpload.js
views/templates/users/codebase.html
views/templates/users/communities.html
views/templates/users/ratings.html

Solution: Refactor a part of the bounty system for easier integration of new bounties, add bounties for wallets, communities and codebase

Problem: Rating wallets, communities, codebase is not bountified (#243)

---

client/users/addCoin.js
server/serverdb/addCoin.js

Solution: add check in submit method, and used check in template state to prevent submit cutting off sanity checks within submit method. #202

Problem: prevent duplicate coin submit

---

client/users/ratings/ratings.js
server/methods/imageUpload.js
views/templates/users/ratings.html

Solution: add functionality for users to see what images they have uploaded therefore allowing them to upload more if required. #267

problem: no way to know if user has uploaded images on ratings

---

client/users/ratings/ratings.js
package-lock.json
package.json
server/methods/imageUpload.js
views/templates/users/ratings.html

solution: add logic to check if three images are uploaded before moving on #281

problem: Ensure three images are uploaded

---

imports/startup/client/routes.js
package-lock.json
views/templates/normal/theme.html

There is no example theme page that people can use when creating a new Bootswatch theme.
Solution: add an example page with all the bootswatch elements

problem: no example theme page

---

views/templates/normal/currencyDetail/currencyDetail.html

solution: remove attribute from template, left over from debugging #283

problem: image filename sometimes displayed

---

client/users/ratings/ratings.js
views/templates/users/ratings.html

solution: display images in bootstrap tooltip instead of new page #282

problem: issue viewing uploaded img

---

client/normal/currency.js
package-lock.json

Solution: show wallt values-min proportionate to max-min. I'm not even sure where wallet field is shown. #194

Problem: radar chart does not maximise available values

---

client/users/addCoin.js
imports/api/coins/methods.js
imports/ui/pages/currencyEdit/currencyEdit.html
imports/ui/pages/currencyEdit/currencyEdit.js
server/serverdb/addCoin.js
views/templates/formHelp/addCoin.html
views/templates/users/addCoin.html

Solution: remove any mentions related to featureTags #196

Problem: featureTags deprecated/clutter

---

lib/properties.js

solution: updated properties.js correctly to reflect production file structure.

problem: properties.js is incorrect

---

.meteor/packages
.meteor/versions
client/users/profile.js
imports/startup/both/routes.js
imports/startup/client/index.js
imports/startup/server/index.js

Solution: use fast-render, install maintained flow-router fork that doesn't cause errors for being on server side too so that it's easier to maintain fast-render with subscriptions along side routes. I haven't deleted original router since the links will stop working. I chiefly inserted subscriptions from top level templates (except for "/bounties"). #197

Problem: DDP latency causes slow loading

---

README.md

solution: update README to include more detailed instructions

problem: instructions can be misinterpreted

---

.meteor/packages
.meteor/versions
client/normal/currency.js
client/normal/desktop.js
client/normal/returnedCurrencies.js
views/layouts/desktop.html
views/layouts/desktop.scss
views/templates/normal/currency.html
views/templates/normal/currency.scss
views/templates/normal/menu.html
views/templates/normal/navbar.html
views/templates/normal/returnedCurrencies.html

Solution : collapsible sidebar navigation added for infinite scroll content and card with minimal info & always visible filter form added

Problem: home route UX does not show enough scope

---

imports/api/hashpower/methods.js
imports/ui/pages/hashpower/flaggedHashpower.js
imports/ui/pages/hashpower/flaggedHashpower.template.html
lib/database/HashPower.js

Solution: Allow moderators to vote on flagged hash power data in order to either remove the data or remove the flag

Problem: Hashpower flagging does not allow removal of flag (#276)

---

client/normal/currencyDetail/fundamentalMetrics.js
imports/startup/both/routes.js
imports/startup/client/routes.js
imports/ui/pages/compareCurrencies/compareCurrencies.js
imports/ui/pages/compareCurrencies/compareCurrencies.template.html
views/templates/normal/currencyDetail/currencyDetail.html
views/templates/normal/menu.html

Solution: Add a dedicated page where users can compare multiple currencies

Problem: No dedicated currency comparison page (#274)

---

AUTHORS
views/layouts/desktop.html
views/layouts/desktop.scss
views/templates/normal/menu.html
views/templates/normal/navbar.html

Solution : Side + Top Navigation should be always fixed and open side navigation inside the scope of top navigation

Problem : Navigations doesn't look nice

---

client/users/wallet.js
imports/startup/both/routes.js
lib/database/UserData.js

Solution: made publicUserData publication that is fast rendered passing it into relevant view.

Problem: trying to reactively use method in /wallet route

---

imports/startup/both/routes.js

Solution: Import the templates accordingly

Problem: Some routes are not rendering (#322)

---

client/users/profile.js
client/users/wallet.js
imports/startup/both/routes.js
lib/api.js
lib/database/UserData.js

Solution: Unify publications since some related ones are global anyway. Formated routes. #320

Problem: UserData publications redundantly numerous

---

client/users/ratings/ratings.js
views/templates/users/ratings.html

solution: add init when invoking modal instead of onRendered which sometimes is unreliable on slower loadtimes #282

problem: tooltips not init every time

---

client/normal/bounties/bounties.js
server/serverdb/rewards.js

Solution: Remove the 'workingBounty' cookie as it could cause problems with starting bounties and format smaller values for nicer display

Problem: Strange reward amounts for ratings (#310)

---

views/layouts/desktop.html

Solution: include sAlert into desktop layout. #327

Problem: Bubble notifications appear to be broken

---

client/normal/menu.js
client/normal/navbar.js
views/templates/normal/menu.html

Solution: implemented notifications in sidebar, removed console error.

Problem: notification badges in sidemenu threw error

---

lib/properties.js

solution: correct incorrect directory location for coin uploads

problem: typo in properties.js

---

client/normal/returnedCurrencies.js
views/templates/normal/returnedCurrencies.html

solution: simplify search bar to a single field and search currencyName & currencySymbol #315

problem: home route search is too complicated

---

client/users/ratings/ratings.js

solution: add more logic to error message/warning message and guide user more correctly #299

problem: upload wallet msg not intuitive

---

.meteor/packages
.meteor/versions
client/normal/currencyDetail/fundamentalMetrics.js
client/normal/navbar.js
imports/startup/both/routes.js
imports/ui/pages/userProfile/userHover.js
imports/ui/pages/userProfile/userHover.template.html
imports/ui/pages/userProfile/userProfile.js
imports/ui/pages/userProfile/userProfile.template.html
lib/database/Currencies.js
lib/database/Features.js
lib/database/UserData.js
lib/database/Users.js
views/templates/normal/currencyDetail/features.html
views/templates/normal/navbar.html

Solution: Implement a basic user profile page with basic user info, currencies the user has added and user's comment history. Also, implement a simple hover template and use the hovercard package to display it properly (on features)

Problem: No public user profiles (#330)

---

client/users/profile.js
imports/ui/pages/userProfile/userHover.template.html
imports/ui/pages/userProfile/userProfile.template.html
lib/database/ProfileImages.js
lib/database/Users.js
lib/properties.js
server/main.js
server/methods/profile.js
views/templates/users/profile.html

Solution: Let users upload profile images from the 'edit profile' page. If the user registers with a social network, his/her image on that social network will be used first.

Problem: Users cannot upload profile image (#348)

---

README.md

Solution: break up readme into collapsible sections, add images, make layout a bit nicer.

Problem: readme is ugly, confronting, and long

---

client/main.css
client/normal/currency.css
client/users/addCoin.js
imports/startup/both/routes.js
server/serverdb/addCoin.js
views/templates/users/addCoin.html

solution: implement bootswatch theme and refactor entire page #352

Problem: add new coin page layout is nasty

---

.meteor/packages
.meteor/versions
client/normal/desktop.js
lib/database/UserData.js

Solution: decouple responsive code from show side bar logic. #350

Problem: sidebar unresponsive to logged-out users

---

server/API_requests/hashpower.js

Solution: Add a hash rate API call for Ethereum

Problem: No hash rate API for Ethereum

---

client/normal/currencyDetail.js

Solution : Remove distribution chart from` currencyDetails.js`

Problem: "graphdata" sub fast rendered on "/currency/.." route fails

---

views/layouts/desktop.scss
views/templates/normal/navbar.html

Solution : Use icons for activity and wallet notification with new notification count and align properly.

Problem : Activity and wallet notification doesn't look nice on top Navigation

---

README.md

Solution: add paid contributor guidelines, tidy up readme.

Problem: no paid contributor guidelines

---

.meteor/packages
.meteor/versions
imports/test/server/unit/elo.test.js
imports/test/server/utils.js

Solution: Implement the Mocha + Chai testing framework with an example test

Problem: Mocha + Chai not used for testing (#367)

---

client/normal/loading.js
imports/ui/pages/flaggedUsers/flaggedUsers.template.html
imports/ui/pages/hashpower/allHashaverage.template.html
imports/ui/pages/hashpower/allHashpower.template.html
imports/ui/pages/userProfile/userProfile.template.html
lib/api.js
views/templates/moderators/questions.html
views/templates/normal/bounties.html
views/templates/normal/currencyDetail/currencyDetail.html
views/templates/normal/currencyDetail/features.html
views/templates/normal/currencyDetail/redflags.html
views/templates/normal/empty.html
views/templates/normal/loading.html
views/templates/normal/returnedCurrencies.html
views/templates/users/activityLog.html
views/templates/users/codebase.html
views/templates/users/communities.html
views/templates/users/developers.html
views/templates/users/ratings.html
views/templates/users/userPendingCurrencies.html

Solution: Made empty and loading templates that render everywhere when needed. I used subscribtion manager's global ready method. #334

Problem: Signaling list's readiness state

---

imports/startup/both/routes.js

Solution: overwrite method used to be Meteor.subscribe, overwrite subscribtion ready checks to true. #379

Problem: subsCache exacerbates bugs in #335

---

client/normal/currencyDetail/redFlagCurrency.js
imports/startup/both/routes.js

Solution: half-arsed solution of just fast-rendering. #359

Problem: when refreshing currency detail page, radar chart loses data

---

client/main.css
client/normal/currencyDetail.js
client/normal/currencyDetail/fundamentalMetrics.js
client/normal/currencyDetail/redFlagCurrency.js
imports/startup/both/routes.js
views/templates/normal/currencyDetail/currencyDetail.html
views/templates/normal/currencyDetail/features.html
views/templates/normal/currencyDetail/redflags.html

solution: add bootswatch elements and css styles #224

problem: comments on the currency detail page dont look very good

---

client/normal/currencyDetail/fundamentalMetrics.js
client/normal/currencyDetail/redFlagCurrency.js
imports/startup/both/routes.js
lib/database/Features.js
views/templates/normal/currencyDetail/features.html
views/templates/normal/currencyDetail/redflags.html

solution: display the tick if you have already voted #361

problem: votes are logged but not visually depicted in UI

---

imports/startup/both/routes.js
imports/ui/components/sideNav/sideNav.html
imports/ui/components/sideNav/sideNav.js
imports/ui/components/sideNav/sideNav.scss
imports/ui/components/topNav/topNav.html
imports/ui/components/topNav/topNav.js
imports/ui/components/topNav/topNav.scss
imports/ui/layouts/mainLayout/mainLayout.html
imports/ui/layouts/mainLayout/mainLayout.js
imports/ui/layouts/mainLayout/mainLayout.scss

Solution : move every ui to imports, currently mainLayout and navigation are moved
#69 
Currently only home layout, side + top navigation are updated and old files are not deleted because that might break inner pages.
Please take a look at file structure, I will do accordingly based on feedback.
cc @anbud @gazhayes

Problem : App architecture inefficiencies

---

client/main.css
imports/ui/components/uploadFormElements.html
imports/ui/pages/hashpower/addHashpower.js
imports/ui/pages/hashpower/addHashpower.template.html
lib/properties.js
package-lock.json
package.json

solution: add better UX to the upload process and import jquery validate (should be rolled out on all client side validation) #349

problem: errors on hashpower page can be confusing sometimes

---

PRODUCTION.md

solution: start documenting production server commands for future reference

problem: production server commands undocumented

---

README.md

Solution: add instructions for writing tests to readme.

Problem: readme is missing information

---

lib/properties.js

solution: fixed properties.js again.. test case is a possible suggestion #406

problem: properties.js wrong value

---

client/normal/currency.css

Solution : Solution : Make graph center by CSS

Problem: currency detail graph is off center #396

---

views/layouts/root.html
views/templates/normal/currency.scss

Solution : Meta tag added for initial screen and resize chart on small screen

problem : home page not responsive

---

.meteor/versions
.travis.yml
imports/test/server/unit/hashpower.test.js

Solution: Add .travis.yml for Travis CI integration, for CI testing

Problem: Repository does not use CI testing (#369)

---

.travis.yml

Solution: Fix the .travis.yml config

Problem: Travis CI tests are failing (#369)

---

production_scripts/mon_script.sh
production_scripts/start_meteor.sh
production_scripts/stop_meteor.sh

solution: write script to detect package changes and run meteor npm install if needed

problem: new packages kill production server

---

production_scripts/HOWTO

solution: add basic instructions

problem: no instructions for scripts

---

.meteor/versions
imports/api/users/server/publications.js
imports/startup/both/routes.js
imports/ui/components/sideNav/sideNav.html
imports/ui/pages/transactions/transactions.js
imports/ui/pages/transactions/transactions.template.html
lib/database/Wallet.js

Solution: Create a paginated view /transactions where users can see all transactions on Blockrazor and the sum of all coins transfered from the main wallet

Problem: No central place to view all transactions (#399)

---

imports/test/server/unit/validateprop.test.js
lib/properties.js

solution: create test script to validate properties.js #408

problem: no test script for properties.js

---

imports/api/indexDB.js

Solution: Imported, #410, #411

Problem: Wallet Images unimported

---

imports/test/server/unit/validateprop.test.js
lib/properties.js

solution: update test script and properties.js to correct value #437

problem: incorrect wallet image directory

---

README.md

solution: add travis build status

problem: travis build status not in readme

---

imports/ui/pages/currencyDetail/currencyDetail.js

Solution: Remove circulating and market cap from editable fields

Problem: Data populated by API should not be editable (#451)

---

imports/ui/pages/changedCurrencies/changedCurrencies.js

Solution: Convert the genesis block date to a human readable format

Problem: Genesis block date change shown in epoch time (#448)

---

imports/ui/pages/currencyDetail/currencyDetail.html
imports/ui/pages/currencyDetail/currencyDetail.js

Solution: Add gitRepo to editable fields

Problem: Cannot propose change to git repository (#452)

---

imports/ui/pages/currencyDetail/currencyDetail.html
imports/ui/pages/currencyDetail/currencyDetail.js

Solution: Convert security model source to a function to prevent initialization with an empty array

Problem: When changing the security model, no data is shown (#450)

---

imports/startup/both/routes.js
imports/ui/components/sideNav/sideNav.js

Solution: commented out left param for BlazeLayout.render

Problem: desktop layout doesn't use left

---

imports/startup/both/routes.js
imports/ui/components/sideNav/sideNav.js

Problem: /decentralization route empty

---

imports/startup/both/routes.js

solution: add trigger in routes to scroll to top of each route change #393

problem: scroll position is not consistent

---

imports/ui/pages/currencyDetail/currencyInfo.html

solution: remove rounded class #397

Problem: currency logos on currency detail page are partially obscured

---

imports/startup/both/routes.js

Solution: layout templates were deleted other than once in import, thus other layout broke. switched all routes to mainLayout.

Problem: fixing site, single layout

---

CONTRIBUTING.MD

problem: dead link in C4

---

imports/ui/pages/bounties/bounties.js
imports/ui/pages/bounties/bountyRender.js

Solution: used session variable. #431

Problem: bounties reward is broken

---

imports/ui/layouts/mainLayout/mainLayout.html

Solution: added ids and alerts

Problem: mainLayout has no alerts, ids

---

imports/api/bounties/server/methods.js

Solution: Bounties imported. #431

Problem: bounties server methods without bounties colleection

---

imports/ui/pages/compareCurrencies/compareCurrencies.js
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

Solution: added some projections, #70

Problems: no client projections causes rerenders

---

lib/database/Bounties.js
server/main.js

Solution: corrected imports, unsolved. #442

Problem: LoggerMongo disabled in main.js

---

imports/ui/pages/addCoin/addCoin.html

Solution: Enabled original message by enabling tooltip. #459

Problem: no tooltip for block time on add currency page

---

imports/ui/pages/addCoin/addCoin.html

Problem: addcoins features section is out of style

---

imports/ui/pages/addCoin/addCoin.html

Solution: tooltips top. and something to do with the fields. #488

Problem: /addcoin unresponsive

---

imports/ui/pages/currencyDetail/walletimages.html
imports/ui/pages/currencyDetail/walletimages.js
server/methods/imageUpload.js

solution: create thumbnail of wallet images and open images in modals #425

Problem: wallet images arent displayed very nicely

---

imports/ui/pages/currencyDetail/walletimages.html

solution: updated wallet img to currect link #425

problem: wallet img has wrong url

---

imports/ui/pages/currencyDetail/comment.html
imports/ui/pages/currencyDetail/feature.html
imports/ui/pages/currencyDetail/redflag.html

solution: add popup hover effect on all occurences of {{author}} #415

problem: profile popovers are broken

---

imports/api/indexDB.js
server/main.js

Solution: Fix the issue by replacing `Applogs` with `AppLogs` in `/imports/api/indexDB`

Problem: LoggerMongo disabled in main.js (#442)

---

imports/ui/components/topNav/topNav.html

solution: add obvious red github link banner #496

problem: no link to github repo

---

imports/ui/pages/addCoin/addCoin.html

solution: style input inline with currency amount field #458

Problem: ICO funds raised layout is bad

---

imports/ui/pages/changedCurrencies/changedCurrencies.html
imports/ui/pages/currencyDetail/currencyInfo.html
imports/ui/pages/currencyDetail/currencyInfo.js

solution: add notes field in modal after saving coin change #453

problem: cannot add notes to proposed changes

---

imports/ui/pages/userProfile/userProfile.html
imports/ui/pages/userProfile/userProfile.js

solution: add mining rig images to profile page #428

problem: mining rig img are not shown on their profile page

---

lib/properties.js

solution: update to correct location #425

problem: watermark location in prop wrong

---

imports/ui/pages/currencyDetail/currencyInfo.js

solution: change edit type for inline edits #504

problem: inline edit doesnt inherit field type

---

imports/ui/layouts/mainLayout/mainLayout.js

Solution : Link removed to deleted file desktop.scss 
PR #514 fix

Problem : Home page breaking

---

imports/test/server/unit/validateprop.test.js

solution: updating validateprop.test.js with correct values for watermark

problem: validateprop.test.js invalid

---

imports/ui/pages/currencyDetail/feature.js

solution:fix dependency error #494

problem: unable to add comments to features

---

imports/ui/components/sideNav/sideNav.scss
imports/ui/layouts/mainLayout/mainLayout.scss

Solution : Fix app-content on opening side navigation, add overlay to app-content to show sideNav prominent on smaller screen

Problem: Active SideNav breaks UI on mobile screen

---

imports/api/auctions/auctions.js
imports/api/auctions/bids.js
imports/api/auctions/server/methods.js
imports/api/auctions/server/publications.js
imports/api/auctions/server/startup.js
imports/api/indexDB.js
imports/startup/both/routes.js
imports/startup/server/fixtures.js
imports/startup/server/index.js
imports/ui/pages/auctions/currencyAuction.js
imports/ui/pages/auctions/currencyAuction.template.html
imports/ui/pages/returnedCurrencies/currency.html
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

Solution: Implement an auction system where users can bid KZR's in order to keep a certain currency on top

Problem: Krazor coins only flowing one way (#427)

---

imports/test/server/unit/hashpower.test.js

Solution: Fix the offending tests by stubbing user data

Problem: Some tests are breaking (#528)

---

imports/ui/pages/addCoin/addCoin.html

solution: fixed template and placement of error message #485

problem: addCoin field messages glitch

---

imports/ui/pages/compareCurrencies/compareCurrencies.html
imports/ui/pages/compareCurrencies/compareCurrencies.js

Solution: icon to the left for generic link icon, rather than external link since fortawesome site breaks on trying to look up fontawesome set: https://fortawesome.com/sets/font-awesome

Problem: compare currencies doesn't link to currencies

---

imports/api/coins/methods.js
imports/ui/pages/auctions/currencyAuction.js
imports/ui/pages/compareCurrencies/compareCurrencies.js
imports/ui/pages/currencyDetail/currencyInfo.html
imports/ui/pages/currencyDetail/currencyInfo.js
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

Solution: When searching for currencies, check previous names as well. Also, show previous names on the currency details page and let users change it

Problem: Currency previous names not utilized (#536)

---

imports/ui/pages/returnedCurrencies/currency.html

Solution: Change the star icon to gavel icon and add a small text `(top bid)` underneath on the winning currency

Problem: Not clear that that users can bid to make currency go to top (#535)

---

imports/ui/pages/compareCurrencies/compareCurrencies.html
imports/ui/pages/compareCurrencies/compareCurrencies.js
package-lock.json
package.json

Solution: combined this- #518- with #526. added typeahead whose styles don't work. stoped typeahead from being moved on the left. added enter as event to add first found option. on selection input doesn't blur nor suggestion menu closes. This is laggy on x6 cpu throttle, perhaps trying to pass tracker.autorun into source option function (to call callback) of typeahead might have been better, although selection appears to require that you destroy and reinit typeahead.

Problem: searching for currency on comparison page is tedious

---

imports/api/rewards/server/methods.js
imports/api/rewards/server/startup.js
imports/startup/server/index.js
imports/ui/pages/currencyDetail/feature.html
imports/ui/pages/currencyDetail/features.html
imports/ui/pages/currencyDetail/redflag.html
imports/ui/pages/currencyDetail/redflags.html

Solution: Reward the top comment/red flag/feature once an hour with 0.1 KZR and place info about the rewards in modals on appropriate pages

Problem: Comments/red flags/features are not incentivised (#430)

---

imports/startup/both/routes.js
imports/ui/pages/compareCurrencies/compareCurrencies.js

Solution: Rewrite route when adding currencies on compare page and use route data (if available) when initializing the page

Problem: Currency comparison page cannot be shared (#530)

---

imports/ui/pages/compareCurrencies/compareCurrencies.html
imports/ui/pages/compareCurrencies/compareCurrencies.js
imports/ui/stylesheets/typeahead.css

solution: use custom css and style to blockrazor, also modify layout to suit #547

problem: currency comparison typeahead is not styled

---

imports/ui/pages/signin/signin.html
imports/ui/pages/signin/signin.js
imports/ui/pages/signin/signin.scss
imports/ui/pages/signup/signup.html
imports/ui/pages/signup/signup.js
imports/ui/stylesheets/_variables.scss

Solution : Update ui-ux of login, signup page

Problem : Login, signup page doesn't look nice

---

client/main.js
imports/api/coins/server/methods.js
imports/api/hashing/server/methods.js
imports/api/users/server/methods.js
imports/startup/both/routes.js
imports/ui/pages/currencyDetail/currencyInfo.html
imports/ui/pages/editProfile/editProfile.html
imports/ui/pages/editProfile/editProfile.js
server/methods/imageUpload.js

solution: create thumbnail gd function on all upload handles and display thumbnail on all views instead of full image #508

problem: thumbnail images do not exist for all upload methods

---

imports/ui/pages/returnedCurrencies/returnedCurrencies.html
imports/ui/pages/returnedCurrencies/returnedCurrencies.js
package-lock.json
package.json

Solution: refractored some code, added use of local collection, used poorly maintained but elaborate library for scrolling, set limit to 15. #543

Problem: "/" route does not use infinite scroll

---

imports/ui/pages/compareCurrencies/compareCurrencies.js

Solution: made autorun that will reinitialize typeahead, which isn't ideal, and i believed it would just work anyway.

Problem: typeahead callback won't switch to local collection

---

imports/ui/pages/compareCurrencies/compareCurrencies.js

Solution: fixed erros caused by moving of code caused typeahead update to transitory collection affecting flow router params.

Problem: fix errors caused by typeahead transitory collection

---

imports/ui/pages/returnedCurrencies/returnedCurrencies.js

solution: change ScrollMagic to scrollmagic

problem: ScrollMagic not always working

---

imports/ui/components/radarGraph.html
imports/ui/components/radarGraph.js
server/methods/elorankings.js

Solution: Count ELO rankings for each currency and calculate global max and min in graph data. To ensure that the data is fresh, calculate it every 10 minutes in cron. Also, show data quality rank underneath the radar chart.

Problem: No metric to determine quantity/quality of existing data (#550)

---

imports/ui/pages/signin/signin.html
imports/ui/pages/signup/signup.html

Solution : Change input type to text from email in UI 
Fixed #568

Problem: email address required to log in

---

imports/ui/pages/returnedCurrencies/returnedCurrencies.js

Solution : Solution : change ScrollMagic to scrollmagic
Related #561

Problem : Error: ScrollMagic is not defined

---

imports/ui/pages/returnedCurrencies/returnedCurrencies.html
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

Solution: "Loading count of results", fixes too #579

Problem: Problem: "Found ... results" doesn't look good

---

imports/ui/components/radarGraph.html
imports/ui/layouts/mainLayout/mainLayout.html
imports/ui/pages/currencyDetail/currency-info.scss
imports/ui/pages/currencyDetail/currencyDetail.html
imports/ui/pages/currencyDetail/currencyInfo.html
imports/ui/pages/currencyDetail/features.html
imports/ui/pages/currencyDetail/fundamentalMetrics.html

Solution : Update UI-UX as per bootswatch, Currency details - feature section collapsible UI added, MainLayout now follow bootswatch
Related to #440 , #577

Problem : currency details ui-ux not good

---

imports/ui/components/radarGraph.html
imports/ui/components/radarGraph.js

Solution: Grey out radar charts if data quality is below 1. Also, add a link where users can contribute more data.

Problem: Radar charts are misleading until there's enough data (#385)

---

imports/api/coins/methods.js
imports/ui/pages/currencyDetail/currencyInfo.html
imports/ui/pages/currencyDetail/currencyInfo.js

solution: add ability to change coin image in modal #585

problem: unable to change coin image

---

imports/api/coins/methods.js
imports/ui/pages/currencyDetail/currencyInfo.js

solution: throw exception if a coin change exists which is pending review #505

problem: users can propose multiple changes on same data point

---

server/API_requests/github.js

Solution: Save errors to the `AppLog` and remove the git repo if it has an error more than 3 times.

Problem: Errors with github API are not self-corrected (#594)

---

imports/ui/layouts/mainLayout/mainLayout.js

Solution: bug related to logged out users. #590

problem: side menu doesn't close automatically on small screens

---

imports/ui/pages/currencyDetail/features.html
imports/ui/pages/currencyDetail/features.js

Solution: implemented load more logic that prefetches next batch. #595

problem: 'features' section on currencydetail route is collapsible

---

imports/ui/pages/wallet/wallet-item.scss
imports/ui/pages/wallet/walletItem.html
imports/ui/pages/wallet/walletItem.js

Solution: applied a width: 100% to wallet-item .card

Problem: weird wallet layout on mobile #596

---

imports/api/indexDB.js
imports/api/rewards/server/methods.js
imports/api/summaries/server/methods.js
imports/api/summaries/server/publications.js
imports/api/summaries/summaries.js
imports/startup/both/routes.js
imports/startup/server/index.js
imports/ui/pages/currencyDetail/currencyDetail.html
imports/ui/pages/currencyDetail/currencyDetail.js
imports/ui/pages/currencyDetail/summaries.html
imports/ui/pages/currencyDetail/summaries.js
imports/ui/pages/currencyDetail/summary.html
imports/ui/pages/currencyDetail/summary.js
package-lock.json
package.json

Solution: Let users add a summary for a certain currency with Markdown support. Show the top summary on the currency detail page, and let users vote on summaries. Reward the top summary every hour.

Problem: No currency summary (#591)

---

.meteor/packages
.meteor/versions
AUTHORS
imports/ui/pages/addCoin/addCoin.html
imports/ui/pages/addCoin/addCoin.js
imports/ui/pages/addCoin/addCoin.scss

Solution: Installed `combodate`; configured `genesisTimestamp` and
`ICODate` to use combodate

Problem: dates on add currency page are not using date pickers #456

---

imports/ui/pages/returnedCurrencies/returnedCurrencies.html

solution: add github logo to homepage #578

Problem: some users are signing up

---

imports/api/coins/server/methods.js
imports/ui/pages/addCoin/addCoin.html
imports/ui/pages/addCoin/addCoin.js

solution: add the attribute in the addcoin page #455

problem:when adding ICO, start time and end time of funding is needed

---

imports/ui/pages/currencyDetail/features.js

solution: looks like jquery toggle breaks collapse items, using bootstrap collapse function instead #604

problem:add feature button breaks after adding a new feature

---

imports/ui/pages/currencyDetail/summaries.html
imports/ui/pages/currencyDetail/summaries.js

solution: remove other hide button and only show one HIDE and SHOW button #610

problem:too many UI elements for currency summaries

---

imports/ui/pages/currencyDetail/fundamentalMetrics.html

problem: compare with other currencies context unaware

---

imports/ui/components/radarGraph.js
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

Solution: start usind parentdata, adjust projection. #599

Problem: /addcoin to main navigation breaks page

---

client/main.js
imports/ui/pages/currencyDetail/commentRender.html
imports/ui/pages/currencyDetail/feature.html
imports/ui/pages/currencyDetail/redflag.html
imports/ui/pages/currencyDetail/redflagComment.html
imports/ui/pages/currencyDetail/summary.html

solution: add global helper to create slugs & update all {{author}} references to navigate to the users profile #619

problem: unable to click usernames

---

imports/api/features/methods.js
imports/ui/pages/moderator/moderatorDash/moderatorPendingCurrency.js

solution: Return error message to user advising them on "why" they can not approve their own currency. #639

problem:no error message when approving own currency

---

imports/ui/pages/currencyDetail/features.js
imports/ui/pages/currencyDetail/redflags.js
imports/ui/pages/currencyDetail/summaries.js

solution: sort createdAt as well as voting rating #611

problem:features/red-flags/summaries/comments are not sorted by rating

---

imports/ui/pages/currencyDetail/features.html

solution: removed `collapsible` related classes; applied btn classes to
the loadMore button

problem: 'features' section on currencydetail route is collapsible #595

---

imports/ui/components/topNav/topNav.html

solution: update navbar to bootwatch darker theme for better constract #630

problem: navbar is white and not dark

---

imports/api/indexDB.js
imports/api/problems/problemComments.js
imports/api/problems/problemImages.js
imports/api/problems/problems.js
imports/api/problems/server/methods.js
imports/api/problems/server/publications.js
imports/api/problems/server/startup.js
imports/startup/both/routes.js
imports/startup/server/index.js
imports/ui/components/sideNav/sideNav.html
imports/ui/pages/moderator/problems/solvedProblems.html
imports/ui/pages/moderator/problems/solvedProblems.js
imports/ui/pages/problems/newProblem.html
imports/ui/pages/problems/newProblem.js
imports/ui/pages/problems/problem.html
imports/ui/pages/problems/problem.js
imports/ui/pages/problems/problemComment.html
imports/ui/pages/problems/problemComment.js
imports/ui/pages/problems/problemComments.html
imports/ui/pages/problems/problemComments.js
imports/ui/pages/problems/problemImages.html
imports/ui/pages/problems/problemImages.js
imports/ui/pages/problems/problems.html
imports/ui/pages/problems/problems.js
lib/properties.js

Solution: Implement a problem system where users can post problems (bug reports, feature requests and questions) and solve problems.

Problem: No way for users to report problems other than on github (#580)

---

imports/ui/components/topNav/topNav.html
imports/ui/pages/bounties/bountyRender.js

Solution: apply text-white text

Problem: topnav logged in view invisible (black text)

---

imports/ui/pages/problems/problem.js

Solution: disabled edit if not owner or if not opened. #647

problem: [/problem] headings and body show as editable in UI for users who can't edit

---

imports/ui/pages/returnedCurrencies/currency.js

Solution: made event for currency/:slug navigation return if even target is icon skipping it's navigation #661

Problem: main route top bids link on currency item navigates twice

---

imports/ui/pages/problems/newProblem.html
imports/ui/pages/problems/newProblem.js
imports/ui/pages/problems/problem.html

Solution: didn't use simplSchema yet, on submit separate meta fields with 2 new lines. summary text: "Summarize problem to solve for in less than 60 characters." unlike related issue solution, will change later. #649

Problem: /newproblem no form guidance between types of form

---

imports/ui/pages/problems/newProblem.html
imports/ui/pages/problems/problem.html

Solution: no bounty field in add question, removed bounty value in question view. added type near bounty field to explain lack of bounty. #648

problem: [/problem] 0 KZR bounty shown for questions

---

imports/ui/pages/currencyDetail/commentRender.html
imports/ui/pages/currencyDetail/commentRender.js
imports/ui/pages/currencyDetail/redflagComment.html
imports/ui/pages/currencyDetail/redflagComment.js

solution: applied `alreadyVotedOnComment` function the comment itsself
instead of parent.

problem: [/currency] when upvoting/downvoting a comment, all comments are marked as "voted" #640

---

imports/ui/pages/problems/problems.html

solution: cleaned up problems page; borrowing from bounty and
currencyDetail pages

problem: [/problems] UX isn't very nice on this route #652

---

imports/ui/pages/problems/problems.html

Solution: added link to problem header redirecting to the single problem
page

Problem: [/problems] no way to navigate to problems/:_id from /problems #669

---

imports/startup/both/routes.js
imports/ui/pages/bounties/bounties.js
imports/ui/pages/bounties/bountyRender.html
imports/ui/pages/bounties/bountyRender.js

Solution: Place problems with rewards into appropriate places at the bounties page.

Problem: Problems with rewards are not on the bounties page (#580)

---

imports/ui/pages/problems/problem.html
imports/ui/pages/problems/problem.js

Solution: Add an UI element where users can add or remove credit from a problem.

Problem: No way for users to add more credit to a problem (#580)

---

imports/api/coins/server/methods.js
imports/api/hashing/server/methods.js
imports/api/indexDB.js
imports/startup/both/devValidationEnabled.js
imports/startup/server/index.js
imports/ui/pages/addCoin/addCoin.js
imports/ui/pages/addHashpower/addHashpower.js
imports/ui/pages/ratings/upload.js

Solution: Remove validation in the development environment with Meteor.isDevelopment, that will generate devValidationEnabled variable that can be overwritten. #667

Problem: validation, and image validation blocks from testing user flows

---

imports/ui/pages/compareCurrencies/compareCurrencies.js

solution: fixed type in import #687

problem: master is broken

---

client/main.js
docs/helpers.md
imports/ui/pages/problems/problems.html
imports/ui/pages/problems/problems.js

solution: add moment.js helper to translate date into a more UX manner. check documentation out within docs/helpers.md #678

problem: datestamp used on items is not very nice

---

imports/ui/components/sideNav/sideNav.html
imports/ui/components/sideNav/sideNav.js
imports/ui/components/sideNav/sideNav.scss
imports/ui/components/topNav/topNav.html
imports/ui/components/topNav/topNav.js

solution:  add KZR balance (truncated to 3 significant figures) to the top nav bar when theres space, and to the top of the sidebar on small screens. #679

problem: balance only displayed inside wallet page

---

imports/ui/pages/problems/problems.html

solution: add bootstrap badge on problems.type #677

problem:not clear which items are problems and which are questions

---

client/main.js
docs/helpers.md
imports/ui/pages/problems/problems.html

solution: create global helper to parse \n to <br /> #676

problem:no line break between problem and solution statement

---

client/main.css
imports/ui/pages/problems/problems.html
imports/ui/pages/problems/problems.js

solution: Disable add problem link unable user has keyup on search. placeholder on search advisers user to search before adding #660

problem:bad UX on add problem link

---

imports/api/hashing/server/hashpower.test.js
imports/api/hashing/server/methods.js
imports/ui/pages/bounties/bounties.js

Solution: indicated source of bug, corrected add hashpower. #637

Problem: [/bounties] add hashpower bounty resets reward on cancel

---

imports/api/users/server/publications.js
imports/startup/both/routes.js

Solution: subscribed to users collection to make constellation's account module work.  #601

Problem: no sample login credentials

---

imports/api/problems/methods.js
imports/ui/pages/problems/newProblem.js

Solution: mutated NaN to 0 before submit instead of original proposed solution. #698

Problem: can't submit question with simplSchema

---

client/main.js
imports/api/common/votes.js
imports/api/features/methods.js
imports/startup/server/index.js
imports/ui/pages/currencyDetail/commentRender.html
imports/ui/pages/currencyDetail/commentRender.js
imports/ui/pages/currencyDetail/feature.html
imports/ui/pages/currencyDetail/feature.js
imports/ui/pages/currencyDetail/redflag.html
imports/ui/pages/currencyDetail/redflag.js
imports/ui/pages/currencyDetail/redflagComment.html
imports/ui/pages/currencyDetail/summary.html
imports/ui/pages/currencyDetail/summary.js

Solution: tracking downvotes; allowing users to change vote;
highlighting type of vote cast

Problem: [/currency] users cannot change their vote on comments/features/red flags/summaries #644

---

imports/api/problems/methods.js
imports/startup/both/index.js
package-lock.json

Solution: corrected isRequiredByDefault, and adjusted error reason generation.

Problem: /new-problem schema enabled always, bad validation errors

---

imports/ui/pages/currencyDetail/feature.html

solution: add back in hovercard helper as it was missing #701

problem:username not displayed on features

---

imports/ui/pages/auctions/currencyAuction.js
imports/ui/pages/auctions/currencyAuction.template.html
imports/ui/pages/compareCurrencies/typeahead.css

solution: implement typeahead into a single field instead of two dom elements #702

problem:bad UX on dropdown

---

imports/api/bounties/server/methods.js
imports/ui/pages/bounties/bounties.js
imports/ui/pages/bounties/bountyRender.html

Solution: begun diffing for values on client side using local collection and then passing on local collection. completely untested. #633

Problem: reason for resetting bounty value is not clear to users

---

imports/api/hashing/server/methods.js
imports/startup/both/routes.js
imports/ui/pages/bounties/bounties.js
imports/ui/pages/bounties/bountyRender.js

Solution: Lock hash power API bounty if someone else is currently working on it.

Problem: Hash power API bounty is not locked (#629)

---

imports/ui/pages/bounties/bounties.html
imports/ui/pages/bounties/bounties.js

Solution: Add a filter on top of the bounties page where users can choose whether they want to work on bounties that require coding skills, bounties for adding new data or bounties for answering questions.

Problem: [/bounties] cannot filter bounties by type (#632)

---

imports/api/ratings/server/methods.js

solution: WalletImages was not imported #722

problem:Exception while invoking method populateRatings

---

imports/api/ratings/server/methods.js
imports/ui/pages/codebase/codCurrencyChoices.html
imports/ui/pages/codebase/codCurrencyChoices.js
imports/ui/pages/codebase/codebase.html
imports/ui/pages/codebase/codebase.js
imports/ui/pages/communities/commCurrencyChoices.html
imports/ui/pages/communities/commCurrencyChoices.js
imports/ui/pages/communities/commQuestions.html
imports/ui/pages/communities/commQuestions.js
imports/ui/pages/communities/communities.html
imports/ui/pages/communities/communities.js
imports/ui/pages/ratings/currencyChoices.html
imports/ui/pages/ratings/question.html

Solution: applied styling to `/communities` and `/codebase`; fixed
currency ratings not using logos

Problem: [/communities] communities page UX not good #716

---

imports/ui/pages/codebase/codebase.js
imports/ui/pages/communities/commQuestions.js
imports/ui/pages/ratings/question.js

solution: check if time btwn 2 answers is < 5, if true reset progress

problem: detecting lazy answering on rating questions isn't robust enough #712

---

imports/ui/components/radarGraph.js
imports/ui/pages/compareCurrencies/compareCurrencies.html
imports/ui/pages/compareCurrencies/compareCurrencies.js
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

Solution: Show only common data points on the radar chart and show other data points on the 'currency compare' page in a form of a bar chart.

Problem: Radar chart not compatible with all blockchain projects (#726)

---

imports/api/coins/server/methods.js
imports/api/hashing/server/methods.js
imports/ui/pages/addCoin/addCoin.html
imports/ui/pages/addCoin/addCoin.js

Solution: Add a way for users to add new algorithms for both PoW and PoS on the 'add currency' page.

Problem: Proof of Stake category doesn't have a sub-category list (#680)

---

imports/api/coins/methods.js
imports/ui/pages/changedCurrencies/changedCurrencies.js
imports/ui/pages/currencyDetail/currencyInfo.js

add exception if mods try to up or down vote their own changes #738

problem: [/changedcurrencies] maintainers (moderators) can merge their own proposed changes

---

imports/api/bounties/server/methods.js
imports/api/communities/server/methods.js
imports/api/developers/server/methods.js
imports/api/hashing/server/methods.js
imports/api/ratings/server/methods.js
imports/api/rewards/server/methods.js
imports/api/utilities.js
imports/api/wallet/server/methods.js
imports/ui/pages/transactions/transactions.html
imports/ui/pages/transactions/transactions.js
lib/properties.js

solution: added reward types site ward and created a filter on the transactions page #733

problem:wallet transfers do not have discrete reasons for transfer

---

imports/ui/pages/compareCurrencies/compareCurrencies.js
server/methods/elorankings.js

Solution: Remove duplicate items from the bar chart and add real hash power data to the chart.

Problem: Bar chart has duplicate items and is missing hashpower data (#734, #735)

---

imports/startup/both/routes.js
imports/ui/components/global/globalHelpers.js
imports/ui/components/sideNav/sideNav.html
imports/ui/components/sideNav/sideNav.js
imports/ui/components/topNav/topNav.html
imports/ui/components/topNav/topNav.js
imports/ui/components/topNav/topNav.scss
imports/ui/pages/bounties/bounties.html
imports/ui/pages/bounties/bounties.js
imports/ui/pages/bounties/bountyRender.html
imports/ui/pages/bounties/bountyRender.js

solution: added badge showing bounty in progress; link to bounty page

problem: hard for user to navigate back to a bounty that is in progress #727

---

imports/ui/pages/userProfile/userProfile.html
imports/ui/pages/userProfile/userProfile.js

solution: refactor page to use bootwatch UI #577

problem: user profile page is not using bootwatch UI

---

README.md

solution: add login credentials

problem: readme does not contain sample login credentials

---

client/main.js
imports/api/users/server/methods.js
imports/ui/pages/userProfile/userProfile.html

solution: was nulling out profilePicture when updating profile, should only update when saving an image #749

problem: profile pictures broken again

---

imports/ui/pages/userProfile/userProfile.html

solution: applied better UX to the comment layout #753

problem:comment history layout is bad

---

imports/ui/pages/userProfile/userProfile.html
imports/ui/pages/userProfile/userProfile.js

solution: only show the edit button when it is your profile page #752

problem:"edit" tab is publicly visible

---

imports/ui/pages/userProfile/userProfile.js

solution: fixed helper, was looking for logged in user, not profile user #751

problem:mining rig pictures not public

---

imports/ui/pages/compareCurrencies/compareCurrencies.html

solution: changed W h/s to just W #767

problem:Hash power unit should simply be W not W h/s

---

imports/startup/both/routes.js
imports/ui/components/topNav/topNav.html

solution: Redirect /profile to profile/slug and remove edit profile button from top nav #769

problem:unnecessary extra profile editing page

---

imports/ui/pages/editProfile/editProfile.js

solution: change redirect to /profile not / #768

problem: profile save redirecting wrong

---

client/main.js
docs/helpers.md
imports/ui/pages/returnedCurrencies/currency.html
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

solution: add attributes on the home screen #723

problem:comparison prices not shown on home route

---

client/main.js

solution: fixed syntax error in code
@gazhayes can you merge ASAP? Looks like something broke when I merged some code in the github browser.

problem:main.js is broken from fixing a merge issue

---

imports/ui/pages/addHashpower/addHashpower.html

solution: bootwatchified the add hash page #777

problem:add hash page is ugly

---

client/main.css
imports/ui/pages/problems/problem.html
imports/ui/pages/problems/problem.js
imports/ui/pages/problems/problemComments.html
imports/ui/pages/problems/problems.html

solution: bootwatchify the problem page #786

problem: problem page is ugly

---

client/main.js
imports/ui/pages/wallet/wallet.html
imports/ui/pages/wallet/wallet.js
imports/ui/pages/wallet/walletItem.html

solution: bootwatchify page and add filter component #746

problem: cannot filter transactions by Type

---

client/main.js

solution: change significance to 5 #723

problem: price,cpc and ctc not displaying

---

imports/ui/pages/editProfile/editProfile.html
imports/ui/pages/editProfile/editProfile.js
imports/ui/pages/userProfile/userProfile.html

solution: add upload helper and better UX to let user know they have changed their profile picture #765

problem: upload does not show progress

---

client/main.js
imports/api/users/server/methods.js
imports/api/users/server/publications.js
imports/api/users/users.js
imports/ui/components/topNav/topNav.html
imports/ui/components/topNav/topNav.js

Solution: Implement an invite system where users can invite friends and earn 5% of what their friends earn daily.

Problem: No incentive for users to invite friends (#756)

---

imports/api/features/methods.js
imports/api/redflags/methods.js
imports/api/summaries/server/methods.js
imports/ui/pages/currencyDetail/features.js
imports/ui/pages/currencyDetail/redflags.js
imports/ui/pages/currencyDetail/summaries.js

Solution: Let users first post 10 features/red flags/summaries and then make them wait 3 days between posting more features/red flags/summaries.

Problem: Users can 'camp' on the top feature/red flag/summary (#785)

---

imports/ui/components/topNav/topNav.html
imports/ui/components/topNav/topNav.js

solution: remove custom CSS and only use bootstrap, add modal instead of dropdown added better title tags to each icon for better UX #799

UX issues with new share button

---

imports/ui/components/topNav/topNav.html

solution: Hide the bounty icon when no bounties are available and clear up the navBar #803

problem: bounty icon visible when none

---

client/main.js
client/root.html
imports/api/coins/server/methods.js
imports/api/communities/server/methods.js
imports/api/developers/server/methods.js
imports/api/features/methods.js
imports/api/miscellaneous/methods.js
imports/api/redflags/methods.js
imports/api/summaries/server/methods.js
imports/api/users/server/methods.js
imports/api/users/server/publications.js
imports/api/wallet/server/methods.js
imports/startup/both/routes.js
imports/ui/pages/currencyDetail/currencyDetail.html
imports/ui/pages/currencyDetail/feature.js
imports/ui/pages/currencyDetail/features.js
imports/ui/pages/currencyDetail/redflag.js
imports/ui/pages/currencyDetail/redflags.js
imports/ui/pages/currencyDetail/summaries.js
imports/ui/pages/moderator/flagged/flagged.html
imports/ui/pages/moderator/flagged/flagged.js
imports/ui/pages/moderator/moderatorDash/moderatorDash.html
imports/ui/pages/moderator/pardon/pardon.html
imports/ui/pages/moderator/pardon/pardon.js
imports/ui/pages/suspended/suspended.html
imports/ui/pages/suspended/suspended.js
package-lock.json
package.json

Solution: Implement a strike system where users earn strikes when they do bad things (submit invalid currencies, cheat on ratings, ...). If a user gets too many strikes, he gets suspended and he can appeal the suspension. Also, implement a captcha system to prevent users from posting comments/red flags/features too fast.

Problem: No way to suspend users who post spam etc (#800)

---

.meteor/packages
.meteor/versions
client/main.js
client/nodatafound.html
imports/ui/pages/wallet/wallet.html
imports/ui/pages/wallet/wallet.js

solution: add new package to render collections in a table and filter/sort #811

problem: unable to filter on amount

---

imports/api/communities/methods.js
imports/api/communities/server/methods.js
imports/startup/both/index.js
imports/ui/pages/communities/commCurrencyChoices.html
imports/ui/pages/communities/commCurrencyChoices.js

solution: Implement validated-method with comments #808

problem:you can save a community url with no values

---

client/main.js
imports/api/miscellaneous/methods.js

Solution: Fix the rendering and the validation issue with recaptcha.

Problem: Recaptcha is not rendering (#800)

---

imports/ui/pages/communities/commCurrencyChoices.html

Solution: hide the file input field #818

problem:adding new community has a really bad UX

---

imports/ui/pages/wallet/wallet.html
imports/ui/pages/wallet/wallet.js

solution: add flag to sort by initial value not the translated value #815

problem:sorting transactions by time doesnt work

---

imports/ui/pages/compareCurrencies/typeahead.css

problem:select currency input cover header

---

imports/api/coins/server/methods.js
imports/api/coins/server/publications.js
imports/api/utilities.js
imports/startup/both/routes.js
imports/ui/components/radarGraph.js
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

Solution: Calculate `quality` field in cryptocurrencies so they can be sorted naturally.

Problem: Coins are not loaded in same order they are displayed (#798)

---

imports/api/communities/methods.js
imports/api/communities/server/methods.js
server/methods/elorankings.js

Solution: Use community size ratio (`community size / community creation time`) as a multiplier (1.2) when calculating ratings for communities.

Problem: Community metric does not take size of community into account (#801)

---

imports/ui/pages/codebase/codebase.js
imports/ui/pages/communities/commQuestions.js
imports/ui/pages/ratings/question.js
lib/properties.js

solution: change to 1 second and as a global param so we can tweak as we progress #821

problem: lazy answering detection is too aggressive

---

imports/ui/pages/problems/problemComments.html
imports/ui/pages/problems/problemComments.js

solution: disabled commenting on closed/cancelled/solved problems

problem: [/problem] users can comment on cancelled problem #838

---

imports/ui/pages/codebase/codebase.js
imports/ui/pages/communities/commQuestions.js
imports/ui/pages/ratings/question.js
lib/properties.js

solution: showing error modals when lazy anwering is detected

Problem: lazy answering errors aren't clear enough #836

---

imports/api/problems/server/methods.js
imports/ui/pages/problems/problem.html

solution: restricting adding bounty to only open problems

problem: [/problem] users can add bounties to cancelled problems #837

---

.gitignore
imports/ui/components/radarGraph.js
imports/ui/pages/returnedCurrencies/currency.html
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

solution: put the top 'red flag' for each currency on the home route.

problem: [/] user generated content not shown on home route #835

---

imports/api/users/server/methods.js
imports/api/users/server/publications.js
imports/api/users/users.js
imports/ui/pages/userProfile/userProfile.html
imports/ui/pages/userProfile/userProfile.js

Solution: Calculate user-based average ranking every 2 hours and display the value on their profile page.

Problem: No user-based average ranking (#832)

---

imports/api/users/server/publications.js
imports/ui/pages/suspended/suspended.js
imports/ui/pages/userProfile/userProfile.html
imports/ui/pages/userProfile/userProfile.js

Solution: Show user's strikes on the profile page.

Problem: User strikes are not shown on profile page (#833)

---

.gitignore
imports/ui/components/radarGraph.js
imports/ui/pages/returnedCurrencies/currency.html
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

solution: revert bad patch #846

problem: home route load order is broken

---

imports/api/problems/server/methods.js
imports/ui/pages/problems/problem.html
imports/ui/pages/problems/problem.js

solution: added reduce() of amount contributed by user in /problem/:id, since /problem doesn't even show bounty. #845

problem: /problem users cant see how much bounty they gave to a problem

---

imports/ui/pages/userProfile/userProfile.html
imports/ui/pages/userProfile/userProfile.js

Solution:  added error template if user reactive var is undefined #760

problem: no 404 for profile pages

---

imports/api/coins/server/methods.js

Solution: put hash algorithm check under if devValidationEnabled.

Problem: addCoin invalidate validation fails for hash algo existence

---

imports/ui/pages/userPendingCurrencies/userPendingCurrencies.html

Solution: changed text to awaiting approval. #792

Problem: /mypending shows pending currency as approved

---

imports/ui/components/topNav/topNav.scss
imports/ui/pages/compareCurrencies/typeahead.css

problem: typeahead menu blocked by amount field

---

imports/api/hashing/server/methods.js
imports/ui/pages/currencyDetail/currencyDetail.html

Solution: Award the user that submitted the PR on the first successful run of the API call. Notify the user is the API call stops working.

Problem: Hashpower API bounty is awarded even if pull request doesn't solve problem (#849)

---

imports/api/users/client/users.js
imports/startup/client/index.js
imports/ui/layouts/mainLayout/mainLayout.js

Solution: Implement a fix for Meteor.logout callbacks to solve the issue.

Problem: Defer call to set user preference for when to open/close sidebar (#565, #862)

---

imports/ui/components/sideNav/sideNav.js
imports/ui/layouts/mainLayout/mainLayout.js

Solution: updated values for it to somewhat work, but it's incomplete. #565

Problem: undefered call to set user preference for sidebar

---

imports/ui/pages/bounties/bounties.js

Solution: just pass the empty string instead of null in case of not signed in.

Problem: #858 bounties not visible unless signed in.

---

imports/ui/layouts/mainLayout/mainLayout.js

Solution: comment out controller until fixed.

Problem: sidebar won't open after responsive close

---

imports/api/utilities.js
imports/ui/components/radarGraph.js
imports/ui/pages/compareCurrencies/compareCurrencies.js

Solution: Implement specific click event handlers for specific areas (labels) on the radar chart and on the bar chart.

Problem: Specific areas on radar graph are not independently actionable (#537)

---

imports/api/bounties/server/methods.js
imports/api/hashing/server/methods.js
imports/ui/pages/bounties/bounties.js

Solution: Fix the helper to ignore expired bounties and remove expired bounties when adding a new one.

Problem: Hashpower API bounties that have timed out are flagged as in progress (#869)

---

imports/ui/pages/problems/problem.html
imports/ui/pages/problems/problem.js

solution: fixed typos on problem page #786

problem: typos in problem page

---

imports/ui/components/typeahead.html
imports/ui/components/typeahead.js
imports/ui/pages/auctions/currencyAuction.js
imports/ui/pages/auctions/currencyAuction.template.html
imports/ui/pages/compareCurrencies/compareCurrencies.js

Solution: converted auctions taking some liberties along the way, removing what I thought is dead code, although i dont understand what options are given that they're not bound to how they're referenced. That is i might have removed the binding. #863

Problem: no typeahead template reuse

---

imports/api/exchanges/exchanges.js
imports/api/exchanges/methods.js
imports/api/exchanges/server/publications.js
imports/api/indexDB.js
imports/api/utilities.js
imports/startup/both/index.js
imports/startup/both/routes.js
imports/startup/server/fixtures.js
imports/startup/server/index.js
imports/ui/components/typeahead.js
imports/ui/pages/compareCurrencies/compareCurrencies.js
imports/ui/pages/currencyDetail/currencyInfo.html
imports/ui/pages/currencyDetail/currencyInfo.js

Solution: made exchange methods/pubs/collections. Expanded localizable collection for optimistic UI. implemented typeahead on target page, but there're major problems with no results found template explained in issue: #783

Problem: [/currency/x] cannot add exchanges to coins

---

client/main.js
imports/api/auctions/server/methods.js
imports/api/auctions/server/startup.js
imports/api/users/server/methods.js
imports/api/users/server/publications.js
imports/startup/both/routes.js
imports/ui/components/sideNav/sideNav.html
imports/ui/pages/addCoin/addCoin.js
imports/ui/pages/auctions/allAuctions.js
imports/ui/pages/auctions/allAuctions.template.html
imports/ui/pages/auctions/bidAuction.js
imports/ui/pages/auctions/bidAuction.template.html
imports/ui/pages/auctions/newAuction.js
imports/ui/pages/auctions/newAuction.template.html
imports/ui/pages/wallet/wallet.html
imports/ui/pages/wallet/wallet.js

Solution: Implement an auction system where users can post auctions or bid to trade Krazors, ETH, XMR and USD. Stub deposits for all currencies on the wallet page.

Problem: No way for users to trade Krazor for other currencies (#844)

---

imports/ui/components/topNav/topNav.scss
imports/ui/layouts/mainLayout/mainLayout.scss

Solution: Change z-index of alert box so that it can be displayed above navigation bar.

Problem: Alert box is displayed behind navigation bar (#898)

---

imports/ui/pages/auctions/newAuction.js
imports/ui/pages/auctions/newAuction.template.html

solution: removed datepicker and added a select to choose the auction period

problem: [/new-auction] auction end dates are hard to choose #895

---

client/main.js
imports/ui/pages/returnedCurrencies/currency.html

solution: dont return significant numbers for prices as this wont mess with the UI from testing #834

problem:prices are not accurate

---

imports/api/communities/methods.js
imports/ui/pages/moderator/moderatorDash/approveCommunityImage.html
imports/ui/pages/moderator/moderatorDash/approveCommunityImage.js
imports/ui/pages/moderator/moderatorDash/moderatorDash.html
imports/ui/pages/moderator/moderatorDash/moderatorDash.js

solution: add approval workflow to moderatorDash screen #782

problem: unable to approve community images

---

imports/api/auctions/server/methods.js

Solution: Remove the last bid after checking if the new bid is higher.

Problem: Adding a new bid lower than the current bid removes existing bid (#909)

---

.meteor/packages
.meteor/versions
imports/api/indexDB.js
imports/api/users/server/publications.js
imports/api/users/users.js
imports/api/users/usersStats.js
imports/startup/both/routes.js
imports/startup/server/fixtures.js
imports/startup/server/index.js
imports/ui/components/typeahead.js
imports/ui/pages/returnedCurrencies/returnedCurrencies.html
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

Solution: Near "found x results" in [/] shows "; Users online: 1/46" #882. Isn't as efficient as I had hoped.

Problem: It's not clear to casual viewers how active the site is.

---

AUTHORS
imports/ui/pages/auctions/bidAuction.js

Solution: change toNow() to fromNow() to get remTime in bidAction.js

Problem: [/auction/x] incorrect momentjs calculations

---

imports/api/utilities.js

solution: added formatAmount fn to correctly format amount before insert

problem: [/wallet] scientific notation sometimes used for amounts #814

---

imports/api/utilities.js
imports/ui/components/radarGraph.html
imports/ui/components/radarGraph.js
imports/ui/pages/compareCurrencies/compareCurrencies.js

Solution: Add an event handler for `mousemove` in order to change the cursor when the user hovering over a label.

Problem: Cursor on chart does not change when hovering (#883)

---

imports/ui/pages/auctions/bidAuction.template.html

Solution: remove double string 'in' in bidAuction template

Problem: [/auction/x] incorrect momentjs calculations #896

---

.gitignore
AUTHORS
imports/ui/pages/returnedCurrencies/currency.html
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

solution: display top red flag on home route.,

problem: no user generated content is shown on home route

---

client/main.js
imports/ui/components/topNav/topNav.scss
imports/ui/layouts/mainLayout/mainLayout.scss
imports/ui/pages/currencyDetail/currencyDetail.html
imports/ui/pages/currencyDetail/currencyDetail.js
imports/ui/pages/currencyDetail/currencyDetail.scss

solution: moved recaptcha to an auto opening modal window

problem: [/currency/x] Recaptcha has bad UI/UX #823

---

imports/api/utilities.js
imports/ui/pages/codebase/codebase.js
imports/ui/pages/communities/communities.js
imports/ui/pages/ratings/currencyChoices.js
lib/properties.js

Solution: added modal warning users of lazy answering detection

Problem: users not warned of lazy answering detection #781

---

imports/ui/pages/wallet/wallet.js
imports/ui/pages/wallet/walletItem.js

solution: changed format of transaction date to display absolute time

problem: wallet transactions shown in relative time #926

---

imports/ui/pages/wallet/wallet-item.scss
imports/ui/pages/wallet/wallet.html
imports/ui/pages/wallet/wallet.scss
imports/ui/pages/wallet/walletItem.js

Solution : Content updated for filter options, No of Rows per page and pagination moved to top for better User Experience
Fix for #929

Problem : Filter in wallet is not clear #929

---

imports/api/ratings/server/methods.js

solution: added if statement checking if question exists

problem: [/rankings] Exception while invoking method 'answerRating' #850

---

imports/api/ratings/server/methods.js

Solution: import `creditUserWith` utility function

Problem: [/ratings] amount not awarded on answered questions #931

---

client/properties.helpers.js
imports/ui/pages/moderator/moderatorDash/approveWalletImage.html

solution: Use global helpers instead of static url #907

problem: approval images are using static urls

---

imports/ui/pages/wallet/wallet.js

solution: validate whether wallet is empty before returning

problem: when a particular currency level is zero, an exception in wallet #939

---

imports/ui/pages/currencyDetail/walletimages.html

Solution: Make modal dialog to be placed center of window and limit image width to dialog width

Problem: [/currency/x] Wallet image modal has invalid align #938

---

imports/api/communities/server/methods.js
imports/api/developers/server/methods.js
imports/api/wallet/server/methods.js
imports/ui/pages/codebase/codebase.html
imports/ui/pages/codebase/codebase.js
imports/ui/pages/communities/commQuestions.html
imports/ui/pages/communities/communities.js
imports/ui/pages/ratings/question.html
imports/ui/pages/ratings/ratings.js
server/methods/elorankings.js

Solution: Divide ELO ranking rewards by the total number of generated questions for that session.

Problem: ELO ranking rewards are multiplied, too much KZR being drained (#935)

---

imports/api/users/server/methods.js

solution: only take strike actions if user is not a moderator

problem: demo moderator account keeps getting suspended #954

---

client/main.css
imports/api/coins/server/methods.js
imports/ui/pages/returnedCurrencies/returnedCurrencies.html
imports/ui/pages/returnedCurrencies/returnedCurrencies.js

solution: add a new filter modal with additional filtering attributes #802

problem: not enough filtering on / route

---

imports/ui/pages/returnedCurrencies/returnedCurrencies.js

problem: slider module was missing and not needed

---

imports/ui/components/sideNav/sideNav.html
imports/ui/components/topNav/topNav.html

solution: changed zrq labels to kzr in navbar and sidebar

Problem: variety of currency codes used instead of KZR #953 reopened

---

imports/ui/components/sideNav/sideNav.scss
imports/ui/layouts/mainLayout/mainLayout.html
imports/ui/pages/currencyDetail/fundamentalMetrics.html
imports/ui/pages/currencyDetail/fundamentalMetrics.js
imports/ui/pages/currencyDetail/redflags.html
imports/ui/pages/currencyDetail/walletimages.html

Solution: using currency-container classes on fundermental metrics; improve Red Flags and Wallet UI

Problem: [/currency/:slug] currencyDetail page not responsive #762

---

imports/ui/pages/returnedCurrencies/returnedCurrencies.html
imports/ui/pages/returnedCurrencies/returnedCurrencies.js
imports/ui/pages/returnedCurrencies/returnedCurrencies.scss
package.json

Solution: replaced date pickers by a slider
Note: added a new dependency -  'bootstrap-slider'
(the modified package.json file also added with this commit)

Problem currency filter is hard to use #984

---

imports/ui/pages/returnedCurrencies/returnedCurrencies.js

solution: fixed DB filter logic for filtering date range

problem: [/] date filter only works in one direction #986

---

imports/ui/pages/returnedCurrencies/returnedCurrencies.js

solution: modified the db query to filter date range correctly

problem: date filter only one direction #986 reopened

---

imports/ui/layouts/mainLayout/mainLayout.html
imports/ui/layouts/mainLayout/mainLayout.js
imports/ui/pages/returnedCurrencies/returnedCurrencies.html

Solution: shows the under evelopment image and the text from modal in a new modal. it is hidden in development env. #982

Problem: active development image is not global

---

imports/api/wallet/server/methods.js
imports/ui/pages/wallet/wallet.html
imports/ui/pages/wallet/wallet.js
imports/ui/pages/wallet/walletTransactions.js
package-lock.json

solution: added notification bubble for respective currency

problem: confusing UX on wallet notifications #968

---

imports/ui/components/typeahead.js
imports/ui/pages/currencyDetail/currencyInfo.js

Solution: param is a function instead that returns value, rather than element id. #1003

Problem: typeahead temp function get value param ought to be function

---

.travis.yml
imports/ui/pages/returnedCurrencies/homepage.ui-test.js
package-lock.json
wdio.conf.js

Solution: Implement webdriverio + headless chrome client side tests in Travis CI and include an example test for the home page. (`homepage.spec.js`)

Problem: No client side tests (#1001)

---

MAINTAINERS

solution: add list of current maintainers

problem: no list of maintainers

---

client/main.css
client/modal.html
imports/api/communities/communities.js
imports/ui/components/sideNav/sideNav.html
imports/ui/pages/moderator/moderatorDash/approveCommunityImage.html
imports/ui/pages/moderator/moderatorDash/approveCommunityImage.js
imports/ui/pages/moderator/moderatorDash/approveWalletImage.html
imports/ui/pages/moderator/moderatorDash/approveWalletImage.js
imports/ui/pages/moderator/moderatorDash/moderatorDash.html
imports/ui/pages/moderator/moderatorDash/moderatorPendingCurrency.html

solution: bootwatchified moderator page #908

problem: moderator page is ugly

---

imports/startup/both/routes.js
imports/ui/components/topNav/topNav.html
imports/ui/pages/faq/faq.html

problem: no FAQ page

---

imports/ui/pages/currencyDetail/currency-info.scss
imports/ui/pages/currencyDetail/fundamentalMetrics.html
imports/ui/pages/currencyDetail/fundamentalMetrics.js

solution: copied homepage currency graph options

problem: [/currency/x] graphs don't scale well #972

---

imports/ui/pages/problems/problem.js

Solution: fixed typo to show error alerts

Problem: [problem/:id] no error message on invalid github url #1013

---

imports/ui/components/sideNav/sideNav.html

Solution: made it to display public menu items for all users

Problem: side menu items not shown unless moderator #1020
