Blockrazor/blockrazor

- imports/api/ratings/server/methods.js
- imports/api/wallet/server/methods.js
solution: marking as read all notifications not assigned currency
> Problem: [/wallet] krazor notifications not being marked as read #1011

- imports/ui/layouts/mainLayout/mainLayout.html
Solution: removed unnecessary captcha component located in layout file
> Problem: [/] Recaptcha always shown in home route #1021

- imports/ui/pages/bounties/bounties.js
Solution: Reset the reward to 1 KZR and calculate from there.
> Problem: Add currency bounty reward too low after reset (#1009)

- AUTHORS
- imports/ui/layouts/mainLayout/mainLayout.html
- imports/ui/layouts/mainLayout/mainLayout.scss
Problem: app content no longer centered when side menu is open #1015
Solution: Adding Active Class Varialbe which is used for side bar detection for styling
> Aaron - Add my name to AUTHOR and Problem: app content no longer centered when side menu is open #1015

- imports/api/bounties/server/methods.js
- imports/api/communities/server/methods.js
- imports/api/developers/server/methods.js
- imports/api/hashing/server/methods.js
- imports/api/wallet/server/methods.js
- imports/ui/pages/bounties/bounties.js
- imports/ui/pages/bounties/bountyRender.html
- imports/ui/pages/bounties/bountyRender.js
Solution: Save the last reward amount and completion time in the main bounty object when a bounty is completed, since individual bounties are removed after the user is rewarded.
> Problem: [/bounties] last reward shown is false (#990)

- .eslintignore
- .eslintrc.yml
- package-lock.json
- package.json
Solution: Implement a simple way to run a linter with `npm run lint`.
> Problem: No project style guide (#934)

- README.md
- STYLES.md
Solution: add style guide.
This is a simple and quick resolution to #934 that only contains javascript styles and does not include Blaze or other Meteor styles.
> Problem: no style guide

- imports/api/communities/server/methods.js
- imports/api/wallet/server/methods.js
- imports/ui/pages/moderator/moderatorDash/approveCommunityImage.js
- imports/ui/pages/moderator/moderatorDash/approveWalletImage.js
solution: add a rejection reason for a moderator and send a notification to the user who uploaded the image #983
> problem: no rejection reason or feedback for comm/wallet images

- client/main.js
- client/root.html
- imports/api/miscellaneous/methods.js
Solution: Import recaptcha dynamically, when needed.
> Problem: Recaptcha imported globally on client (#981)

- imports/ui/pages/communities/commCurrencyChoices.html
- imports/ui/pages/communities/commCurrencyChoices.js
- imports/ui/pages/communities/communities.html
- imports/ui/pages/communities/communities.js
solution: add a tick to the button if users have uploaded an image #1042
> problem: Its unknown what community images you have uploaded

- README.md
solution: add blockrazorbot instructions.
> problem: blockrazorbot instructions not in readme

- imports/ui/pages/compareCurrencies/compareCurrencies.html
- imports/ui/pages/compareCurrencies/compareCurrencies.js
Solution: changed chart responsive opt to true and wrapped table in
.table-responsive
> Problem: [/compareCurrencies] compareCurrency page not responsive #1054

- imports/api/auctions/auctions.js
- imports/api/auctions/bids.js
- imports/api/hashing/hashAlgorithm.js
- imports/api/hashing/hashAverage.js
- imports/api/hashing/hashHardware.js
- imports/api/hashing/hashUnits.js
Solution:  Did everything but votes and trivial collections. #272
> Problem: No schemas on collections

- imports/api/users/users.js
solution: required file was only avilable on the server and not client #1066
> problem: users cannot log in

- imports/ui/pages/currencyDetail/currencyInfo.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
Solution: removed userstats and exchanges.
> Problem: collection global/window bindings

- imports/startup/both/routes.js
Solution: increased limit to 15 from 10. corrected error in subscription.
> Problem: SubsCache limit can't accomodate some pages

- imports/ui/pages/currencyDetail/feature.html
- imports/ui/pages/currencyDetail/feature.js
- imports/ui/pages/currencyDetail/redflag.html
- imports/ui/pages/currencyDetail/redflag.js
solution: add a reply button when there are no comments and focos on input for better UX #978
> problem: UX was confusing on no messages

- imports/ui/pages/compareCurrencies/compareCurrencies.js
Solution: deleted return statement and added filter for duplicates in
dataset
> Problem: [/compareCurrencies] Chart data lost on page refresh #1055

- imports/api/bounties/server/publications.js
- imports/api/coins/server/publications.js
- imports/api/problems/server/publications.js
- imports/startup/both/routes.js
- imports/ui/pages/bounties/bounties.js
- imports/ui/pages/bounties/bountyRender.js
Solution: Implement a way to limit the number of documents returned for bounties. Sort documents before limiting to ensure that only highest rewards will be shown.
> Problem: No query projection limit on [/bounties] (#980)

- imports/ui/pages/userPendingCurrencies/userPendingCurrencies.html
- imports/ui/pages/userPendingCurrencies/userPendingCurrency.js
Solution: removed dead code lines in template and added checks for variables
> Problem: [/mypending] type error in console #1078

- imports/ui/components/topNav/topNav.html
solution: remove logo on mobile and add bounties #631
> problem: header is cluttered on mobile

- imports/api/problems/methods.js
- imports/api/problems/problems.js
Solution: converted it schema defined on collection
> Problem: newProblem method used own schema

- imports/ui/components/sideNav/sideNav.html
- imports/ui/components/sideNav/sideNav.js
- imports/ui/components/sideNav/sideNav.scss
- imports/ui/components/topNav/topNav.html
- imports/ui/components/topNav/topNav.js
- imports/ui/layouts/mainLayout/mainLayout.js
- package-lock.json
- package.json
solution: add better UX with the header and use hammerJS to slide open and shut the menu on mobile devices #1080
> problem: bad UX when closing side menu

- imports/ui/components/topNav/topNav.html
solution: add logo in header when on mobile #631
> problem: logo is not in header when mobile

- .babelrc
- imports/api/activityLog/methods.js
- imports/api/bounties/methods.js
- imports/api/communities/methods.js
- imports/api/ratings/methods.js
- imports/api/wallet/methods.js
- imports/ui/components/typeahead.jest-test.js
- package-lock.json
- package.json
Solution: Configure babel (babel-jest) to enable usage of es6 code and es6 modules in testing environment, and add an example test script.
> Problem: Jest testing implementation not working (#1059)

- imports/api/redflags/server/publications.js
- imports/startup/both/routes.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
Solution: Add a subscription for `redflags` to the `/` route in the router.
> Problem: [/] fast render doesn't work (#1051)

- imports/api/wallet/methods.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
- imports/ui/pages/transactions/transactions.js
solution: refactored code with error handling to resolve issues. (more to come)
> problem: various console issues causing possible issues

- client/main.js
- imports/api/utilities.js
solution: add catch on function to not run if variable is null therefore removing console error spam #1092
> problem: error in console relating to populateLocal method

- imports/ui/pages/codebase/codebase.html
- imports/ui/pages/codebase/codebase.js
- imports/ui/pages/codebase/codebase.scss
- imports/ui/pages/ratings/question.html
- imports/ui/pages/ratings/question.js
- imports/ui/pages/ratings/ratings.scss
solution: modified UI to display equal option properly
> problem: [/ratings, /codebase] cannot see equal to item #1094

- imports/ui/pages/moderator/moderatorDash/moderatorPendingCurrency.html
- imports/ui/pages/moderator/moderatorDash/moderatorPendingCurrency.js
- imports/ui/pages/ratings/question.html
solution: properly open and close new currency inspection modal
> problem: [/moderator] cant take reject actions #1095

- imports/ui/components/topNav/topNav.html
- imports/ui/components/topNav/topNav.scss
Solution: add bounties menu item to top nav
> Problem: no encougement to look at bounties page #1100

- imports/api/distribution/methods.js
- imports/api/problems/methods.js
- imports/api/utilities.js
- imports/startup/both/index.js
- imports/startup/both/routes.js
- imports/ui/components/sideNav/sideNav.html
- imports/ui/pages/distribution/distribution.html
- imports/ui/pages/distribution/distribution.js
Solution: Calculate spending and earning projections for 1 month, 6 months and 1 year and display them on `/distribution` page.
> Problem: No krazor distribution metrics (#1102)

- imports/api/analytics.js
- imports/api/auctions/methods.js
- imports/api/users/users.js
- package-lock.json
- package.json
solution: Implement segmentIO to track certain user events #964
> problem: cant track user actions

- imports/ui/pages/problems/newProblem.html
solution: move summary field below the problem details fields
> problem: [/new-problem] summary requested before details #1111

- imports/ui/pages/addHashpower/addHashpower.html
Solution: restyled add-hashpower ui
> Problem: [/add-hashpower] form ui/ux not good #1077

- imports/api/users/server/startup.js
- imports/api/users/users.js
- imports/api/users/usersStats.js
- imports/startup/server/index.js
Solution: Move the server part of the code to a separate file, as `usersStats.js` has to be loaded on the client as it's imported a few times on the client.
> Problem: A server file makes it into client bundle (#913)

- imports/api/users/methods.js
- imports/api/users/server/publications.js
- imports/ui/pages/bounties/bounties.html
- imports/ui/pages/bounties/bounties.js
- imports/ui/pages/bounties/bounties.scss
solution: implemented checkbox based filtration instead of select
> problem: [/bounties] filtering is annoying to use #1110

- client/main.css
- imports/ui/components/topNav/topNav.html
- imports/ui/components/topNav/topNav.scss
- imports/ui/layouts/mainLayout/mainLayout.html
- imports/ui/layouts/mainLayout/mainLayout.scss
solution: refactor topNav to use the bootwatch style #1108
> problem: topNav not bootwatchified

- imports/ui/components/sideNav/sideNav.scss
- imports/ui/components/topNav/topNav.html
- imports/ui/components/topNav/topNav.scss
solution: change to dark theme so no custom CSS and reduce header size #1108
> Problem: top navbar menu looks bad, is not using bootswatch

- imports/api/coins/currencies.js
- imports/api/coins/server/publications.js
- imports/startup/both/routes.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
Solution: Prevent infinite scroll from triggering on initial load keeping sub params identical to fast-render's. Corrected returned currencies behaviour on which solution depended. #1116 #1072 Fast-render payload: ``FastRender._payload.subscriptions.dataQualityCurrencies``
> Problem: [/] fast render failing and otherwise sending every document

- imports/startup/both/routes.js
- imports/ui/pages/auctions/bidAuction.js
- imports/ui/pages/auctions/bidAuction.template.html
Solution: Show the price per Krazor on the auction page (both in the base currency and in USD) and show USD prices for the highest bid.
> Problem: Auctions do not show the price per Krazor (#1126)

- imports/ui/pages/problems/problems.html
Solution: Use what all the other lists are using with else in each block and a global helper for SubsCache.ready().
> Problem: [/problems] doesn't have list readiness messages (#1124)

- imports/ui/pages/problems/problems.js
Solution: Prevent form submission on enter keypress.
> Problem: Pressing enter on text filter in problems will refresh page (#1123)

- imports/api/bounties/methods.js
- imports/api/coins/methods.js
- imports/ui/pages/moderator/moderatorDash/moderatorPendingCurrency.js
Solution: moved the removal code outside of the callback of async insert function
> Problem: [/moderator] approved currencies not cleared

- imports/startup/server/index.js
solution: import methods on server, they were removed #1141
> problem:cannot change currency logo

- imports/ui/components/topNav/topNav.scss
solution: changed header links to white with a grey hover which offers a better UX #1134
> problem: header links are hard to see

- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
Solution: Before destroying old subscription wait for new one to ready. #1145
> Problem: [/] infinite scroll forces user back to top of page #1145

- client/main.js
Solution: Made custom allReady function implemented for global blaze helper that's responsible for displaying ready message. #1144
> Problem: "Loading" everywhere, refresh often needed

- imports/api/auctions/methods.js
- package.json
Solution: Don't allow users to cancel auctions that already have bids.
> Problem: Users can cancel auctions after bids have been placed (#1147)

- imports/api/users/methods.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
Solution: Add information about the number of new users (signed up in the last 30 days) on the home route.
> Problem: No indication of how many users have recently signed up (#1143)

- imports/ui/pages/auctions/allAuctions.js
- imports/ui/pages/auctions/allAuctions.template.html
- imports/ui/pages/auctions/bidAuction.js
- imports/ui/pages/auctions/bidAuction.template.html
Solution: moved cancel button to auction details page
> Problem: [/auctions] only creater should see cancel option #1150

- imports/ui/components/topNav/topNav.html
- imports/ui/components/topNav/topNav.scss
Solution: removed additional wallet icon from large screens
> Problem: [navbar] wallet icon is redundant #1163

- imports/startup/both/routes.js
- imports/ui/pages/auctions/allAuctions.js
- imports/ui/pages/auctions/allAuctions.template.html
Solution: Show the highest bid and the price per KZR on the `/auctions` page as well.
> Problem: Users have to click into an auction to see the highest bid (#1153)

- imports/api/wallet/methods.js
- imports/ui/pages/transactions/transactions.html
- imports/ui/pages/transactions/transactions.js
Solution: Fix the helper for showing the amount and fix the calculation of the total coin count.
> Problem: Incorrect total and NaN for amounts on transactions (#1168, #1169)

- imports/ui/components/topNav/topNav.html
- imports/ui/components/topNav/topNav.scss
Solution: added icon logo for small screens
> Problem: [navbar] icon logo missing on small screens #1165

- imports/api/users/server/startup.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
Solution: Update the new users count every 3 hours in a cron job, and store the data in `UsersStats` collection which is already loaded on the home route.
> Problem: "New users in the last month" loads slowly (#1166)

- imports/api/auctions/methods.js
Solution: Change `<` to `<=` in the `placeBid` method.
> Problem: Users can outbid by placing same bid as last bidder (#1171)

- imports/api/coins/methods.js
Solution: moved client ip detection part to a server-only block
> Problem: [/changedcurrencies] Exception when voting #1167

- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.scss
solution: refined project show/hide filters
> probem: [/] cannot hide launched projects #1170

- imports/ui/pages/transactions/transactions.js
Solution: returning the actual amount in amount function
> Problem: [/transactions] incorrect amounts displayed #1183

- imports/ui/pages/auctions/allAuctions.js
- imports/ui/pages/auctions/allAuctions.template.html
solution: remove auction name from table #1149
> problem: auction name is displayed but not necessary

- imports/ui/pages/wallet/wallet.html
solution: update image handler to look for etherium #1127
> problem: wallet image not loading

- imports/ui/pages/auctions/newAuction.template.html
solution: change the html step value to 0.00001 #1185
> problem:cannot bid small amounts

- imports/ui/pages/auctions/allAuctions.js
solution: filter was searching closed:null when I refactored code to be false as null is bad for consistancy #1200
> problem: new auctions are missing

- imports/api/activityLog/methods.js
- imports/api/coins/server/methods.js
- imports/api/communities/methods.js
- imports/api/developers/methods.js
- imports/api/ratings/methods.js
- imports/api/users/users.js
- imports/api/utilities.js
- imports/api/wallet/methods.js
- server/API_requests/github.js
- server/main.js
- server/methods/elorankings.js
Solution: Move the `log` function from `/server/main` to `/imports/api/utilities` and update references in order to fix the referencing error. Importing from `/server/main` always returned undefined.
> Problem: [/communities] ReferenceError: log is not defined (#1198)

- imports/ui/layouts/mainLayout/mainLayout.html
- imports/ui/layouts/mainLayout/mainLayout.scss
- imports/ui/pages/compareCurrencies/compareCurrencies.html
- imports/ui/pages/compareCurrencies/compareCurrencies.js
- imports/ui/pages/compareCurrencies/compareCurrencies.scss
Solution: optimized the UI of compare currencies page
> Problem: [/comparecurrencies] graphs are too big #1204

- imports/ui/pages/wallet/wallet.html
> Problem: [/wallet] ETH notifications always 0 #1188

- imports/ui/pages/returnedCurrencies/homepage.ui-test.js
Solution: Write a relatively simple test for the '/' route as an example how to check for this.
> Problem: Changes to subscription parameters can easily break subscache (#1196)

- MAINTAINERS
solution: add Samuel to list of Maintainers
> problem: Samuel is not listed as a maintainer

- .meteor/packages
- .meteor/versions
> Problem: appcache breaks fast-render

- imports/ui/components/sideNav/sideNav.html
Solution: added Home menu item to sidebard
> Problem: no home link in sidebar #1217

- imports/api/indexDB.js
- imports/api/launchEmails/launchEmails.js
- imports/api/launchEmails/methods.js
- imports/startup/both/index.js
- imports/ui/layouts/mainLayout/mainLayout.html
- imports/ui/layouts/mainLayout/mainLayout.js
solution: add email field in the under dev modal #1201
> problem: users cannot add an email address to be notified on launch

- imports/ui/layouts/mainLayout/mainLayout.js
Solution: added navigation menu helper
> Problem: side navigation menu missing #1228

- client/main.js
soltion: use subcache on the UserData collection #1184
> problem:moderator dashboard link randomly disappears

- imports/ui/pages/auctions/newAuction.js
- imports/ui/pages/auctions/newAuction.template.html
solution: use bootstrap validation at field level not not ugly sAlerts #1185
> problem:cannot bid on small amounts

- imports/api/users/server/publications.js
solution: add another level of catching on the moderator attribute
> problem: travis failing

- imports/ui/pages/currencyDetail/currencyDetail.html
Solution: removed comment of recpatcha html code
> Problem: [/currency/x] recaptcha missing #1241

- imports/ui/components/typeahead.js
- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: Made things work with unstyled button, it turns out the typeahead component isn't so hot on reacting to external changes and will run add twice in some instances. #1236
> Problem: [/currency/x & /addcoin] cannot add exchanges to currencies

- imports/api/users/methods.js
- imports/api/users/server/publications.js
- imports/api/users/server/startup.js
- imports/startup/both/routes.js
- imports/ui/components/sideNav/sideNav.html
- imports/ui/pages/moderator/candidates/candidates.html
- imports/ui/pages/moderator/candidates/candidates.js
Solution: Generate a list of possible moderators every 24 hours on which moderators can vote to either approve or deny new moderators.
> Problem: Not possible to add new moderators/maintainers (#1230)

- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.scss
Solution: put add exchange button next to the typeahead
> Problem: [/currency/:x] add exchange button decoupled #1246

- imports/ui/pages/addCoin/addCoin.html
- imports/ui/pages/addCoin/addCoin.scss
Solution: added proper style classes
> Problem: [/addcoin] overflows behind sidebar #1249

- imports/api/users/methods.js
- imports/api/users/server/publications.js
- imports/ui/pages/userProfile/userProfile.html
- imports/ui/pages/userProfile/userProfile.js
Solution: Add the overall user rank field (rating and ranking) to the user's profile page.
> Problem: No overall user rank (#1257)

- .meteor/packages
- .meteor/versions
- client/compatability/bootstrap3-editable/js/bootstrap-editable.js
Solution: Remove `mrt:combodate` package and bump the version of `combodate` from 1.0.5 to 1.0.7 in `bootstrap3-editable`.
> Problem: [/currency/x] Cannot edit genesis timestamp (#1256)

- imports/ui/pages/currencyDetail/currencyInfo.scss
Solution: changed element styles to display properly
> Problem: [/currency/x] detail edit buttons overflows parent #1255

- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: modified validations of add exchange
> Problem: [/currency/x] cant read map of undefined #1259

- imports/api/exchanges/methods.js
Solution: modified validation checks
> Problem: add exchange backend validation #1266

- imports/ui/components/topNav/topNav.scss
Solution: made text white color only applicable for navbar elements
(and not for dropdown menu items)
> Problem: User profile dropdown menu invisible #1274

- imports/ui/pages/wallet/wallet.html
- imports/ui/pages/wallet/wallet.js
- imports/ui/pages/wallet/wallet.scss
Solution: display images in similar height
> Problem: [/wallet] wallet images are in different sizes #1281

- imports/ui/components/typeahead.js
Solution: Prevent double initialization of typeahead.
> Problem: Typeahead triggers add event twice on select (#1247)

- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: set it unfocused when render
> Problem: [/currency/x] typeahead focused when render #1284

- imports/ui/pages/currencyDetail/currencyDetail.scss
- imports/ui/pages/currencyDetail/features.js
- imports/ui/pages/currencyDetail/redflags.js
solution: remove scrolling and make use of the more loadmore button #1273
> problem: its not obvious that red flags/features are scrollable

- imports/ui/pages/currencyDetail/currencyDetail.html
- imports/ui/pages/currencyDetail/currencyDetail.js
Solution: added helper function getting currencySymbol from currency
> Problem: compare with other currencies does not populate currency comparison page #1288

- imports/startup/both/routes.js
- imports/ui/components/sideNav/sideNav.html
- imports/ui/pages/exchanges/exchanges.html
- imports/ui/pages/exchanges/exchanges.js
- imports/ui/pages/exchanges/exchanges.scss
solution: add an index to list all exchanges #1285
> problem: no page listing all the exchanges

- imports/api/auctions/methods.js
- imports/ui/components/typeahead.js
Solution: Check if the currency has been selected and if it exists before placing a bid.
> Problem: Able to bid with no currency (#1296)

- imports/ui/pages/currencyDetail/redflag.html
solution: typo in code showing featureName instead of name #1271
> Problem: red flag text doesnt display

- imports/ui/components/topNav/topNav.scss
- imports/ui/pages/addCoin/addCoin.html
- imports/ui/pages/problems/problems.html
solution: create new header on two pages for review #1294
> problem: no consistency in headers

- imports/startup/both/routes.js
- imports/ui/components/sideNav/sideNav.html
- imports/ui/components/sideNav/sideNav.js
- imports/ui/components/sideNav/sideNav.scss
solution: highlight the page you are on using flowrouter Routes #1291
> problem: Its not obvious what page you are on

- imports/ui/pages/activityLog/activityLog.html
- imports/ui/pages/auctions/allAuctions.template.html
- imports/ui/pages/auctions/newAuction.template.html
- imports/ui/pages/bounties/bounties.html
- imports/ui/pages/compareCurrencies/compareCurrencies.html
- imports/ui/pages/currencyDetail/currencyDetail.html
- imports/ui/pages/distribution/distribution.html
- imports/ui/pages/exchanges/exchanges.html
- imports/ui/pages/wallet/wallet.html
solution: add new header template to all pages which have been styled, others can be added when styled #1294
> problem: no consistency in page headers/labels

- imports/ui/pages/currencyDetail/features.js
- imports/ui/pages/currencyDetail/redflags.html
- imports/ui/pages/currencyDetail/redflags.js
Solution: Fix conflicting limits for `Features` and implement the 'load more' logic for `Redflags`.
> Problem: Load more button on currency page doesn't work (#1301)

- imports/ui/components/sideNav/sideNav.js
- package-lock.json
- package.json
solution: remove hammerjs and swipe gestures #1305
> problem:swipe gestures on mobile are annoying

- imports/ui/pages/activityLog/activityLog.html
- imports/ui/pages/activityLog/messageitem.html
solution: bootwatchified the notifications page #1289
> problem: notification page is not bootwatchified

- imports/api/activityLog/methods.js
- imports/api/features/methods.js
- imports/api/problems/methods.js
- imports/api/redflags/methods.js
- imports/ui/pages/activityLog/messageitem.html
Solution: Notify users when someone comments on their feature/red flag/problem and link to the correct page from notifications page.
> Problem: Users aren't notified when someone replies to their comment (#1308)

- .gitignore
- imports/ui/components/typeahead.html
- imports/ui/components/typeahead.js
- imports/ui/pages/addCoin/addCoin.html
- imports/ui/pages/addCoin/addCoin.js
- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: refractored typeahead: create button now in typeahead template and is on [/addcoin] #1236, and made it disable #1311, made create button reflect added item reverting behaviour where exchange was created and added automatically #1314.
> Problem: [/addcoin] exchanges typeahead; typeahead fixes

- client/compatability/smart_wizard.css
- imports/startup/both/routes.js
- imports/ui/pages/addCoin/addCoin2.html
- imports/ui/pages/addCoin/addCoin2.js
- package-lock.json
- package.json
solution: add a wizard to break the page up a little (draft) #1280
> problem: add coin is complex

- imports/api/auctions/methods.js
- imports/api/indexDB.js
- imports/api/payments/payments.js
- imports/api/payments/server/methods.js
- imports/api/payments/server/startup.js
- imports/api/users/methods.js
- imports/api/users/server/publications.js
- imports/startup/server/index.js
- imports/ui/pages/wallet/wallet.html
- imports/ui/pages/wallet/walletTransactions.html
- imports/ui/pages/wallet/walletTransactions.js
- lib/properties.js
- package-lock.json
- package.json
Solution: Implement a way for users to deposit XMR from the testnet. Provide them with the payment address and payment id on the wallet page.
> Problem: Users cannot deposit Monero into their wallet (#1313)

- imports/ui/pages/returnedCurrencies/currency.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.scss
Solution: added font-awesome exclamation mark and positioned redflag in better space in the card
> Problem: [/] red flags on currency cards are not obvious #1325

- imports/ui/components/typeahead.css
- imports/ui/components/typeahead.html
- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.scss
Solution: changed styles to display create button on the same line as typeahead
> Problem: typeahead create button appear on next line #1316

- imports/ui/pages/returnedCurrencies/currency.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.scss
Solution: moved top redflag label to next line
> Problem: [/] redflag label overwrites contribute data #1331

- imports/ui/components/typeahead.css
- imports/ui/components/typeahead.html
- imports/ui/pages/addCoin/addCoin.html
- imports/ui/pages/addCoin/addCoin.js
- imports/ui/pages/addCoin/addCoin.scss
- imports/ui/pages/addCoin/addCoin2.html
- imports/ui/pages/addCoin/addCoin2.js
Solution: replaced table with a list
> Problem: [/addCoin] exchanges appear in a table #1330

- imports/ui/pages/problems/newProblem.html
- imports/ui/pages/problems/newProblem.js
Solution: implement a modal to display importance message if user not selected amount to donate while still having some kzr in his wallet
> Problem: importance of adding bounty to bug reports #1343

- imports/ui/components/sideNav/sideNav.scss
- imports/ui/layouts/mainLayout/mainLayout.html
- imports/ui/layouts/mainLayout/mainLayout.js
- imports/ui/layouts/mainLayout/mainLayout.scss
On addition to implementing the button (that basically does the same as the burger menu on the navbar) some sizing/positioning issues have been fixed in the sidebar.
> problem: not obvious how to close side menu

- .meteor/packages
- .meteor/versions
- imports/ui/pages/addCoin/addCoin.js
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: make it add created exchange from callback #1315
> Problem: [currency/:x] typeahead create exchange can't add

- imports/ui/components/typeNX.js
- imports/ui/components/typeahead.html
- imports/ui/components/typeahead.js
- imports/ui/pages/addCoin/addCoin.js
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: used nx-framework keeping old api for external button.  Introduces bug for navigaiton. Converts current usage to non-button one.#1346
> Problem: injecting reactive create button into typeahead

- AUTHORS
- imports/startup/both/routes.js
- imports/ui/pages/returnedCurrencies/currency.js
Solution: Replaced weird waitOn() with async/await.
> Problem: [/] broke after being dynamically imported #1352.

- imports/ui/components/typeahead.html
- imports/ui/components/typeahead.js
Solution: removed error by not using script tag for cdn and importing a lib simultaneusly. reduced number of middlewears.
> Problem: remove error produced by bad import for nx-framework

- imports/startup/both/routes.js
solution: Believe issues are relating to dynamic imports and code was removed #1370
> problem: cant navigate to addCoin page

- imports/ui/components/typeahead.js
Solution: pass current value into cursor observer that updates typeahead source, and made the value reseting behaviour more so conditional. reverted changes that broke enter event. #1319
> Problem: typeahead doesn't react to mongo cursor change #1319

- imports/ui/components/typeahead.html
Solution: Disable autocomplete on typeahead.html
> Problem: autocomplete interferes with typeahead (#1380)

- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: Revert the changed values in the hidden input fields when the user clicks cancel.
> Problem: not saving changes on [/currency/:x] in modal will not revert changes.

- imports/startup/client/index.js
Solution: first step is reducing bundle size.
> Problem: no lighthouse audit (#1359).

- imports/api/coins/currencies.js
- imports/api/coins/methods.js
- imports/ui/pages/addCoin/addCoin.html
- imports/ui/pages/addCoin/addCoin.js
solution: add ability to add smart contract data and smart contract URL from addCoin #1324
> problem: smart contracts cannot be added

- imports/ui/components/typeahead.js
Solution: change conditions for doing that, I don't know how last nights fix didn't fix anything.
> Problem: typeahead incercepts input (resetting/blurring)

- imports/ui/pages/addCoin/addCoin.js
Solution: Filter the 'Hybrid' category.
> Problem: Hybrid security model shows PoS and PoW (#1386).

- AUTHORS
- imports/ui/pages/addCoin/addCoin.html
- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.js
solution: add smart contract URL to the currencyDetail screen #1389
> problem: smartContractURL not visible anywhere

- imports/api/exchanges/methods.js
- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.js
- imports/ui/pages/currencyDetail/currencyInfo.scss
- imports/ui/pages/exchanges/exchanges.html
- imports/ui/pages/exchanges/exchanges.js
Solution: added untag button for [/currency/x] exchanges and added delete button for [/exchanges] table entries
> Problem: [/currency/x] exchanges cannot untagged #1344

- imports/ui/pages/addCoin/addCoin.html
solution: Add blaze helpers to show correct labels depending if smart contract is checked #1394
> problem: smart contract selection does not update fields correctly

- imports/startup/both/routes.js
- imports/ui/pages/editProfile/editProfile.js
- imports/ui/pages/userProfile/userProfile.html
solution: import editProfile.js/html in routes.js #1415
> problem: No such template: editProfile

- imports/ui/components/radarGraph.html
- imports/ui/pages/returnedCurrencies/currency.html
- imports/ui/pages/returnedCurrencies/currency.js
solution: clean the UI up a little, add tooltips to prices #1396
> problem: currency cards dont look very good

- imports/ui/components/typeNX.js
solution :Revert old typeNX.js code.
> Problem : After merge PR #1422 conflict in typeNX.js

- imports/api/features/methods.js
- imports/ui/pages/currencyDetail/features.js
- imports/validate/featuresValidate.js
Solution: Add client side validation before call meteor method for  in [/currency/:X] page.
> Problem: No client-side validation on add-feature form #1404

- imports/ui/components/sideNav/sideNav.scss
- imports/ui/layouts/mainLayout/mainLayout.scss
Solution : Add css for sidemenu close icon in sideNav.scss and mainLayout.scss.
> Problem : Sidemenu close button position not center #1428

- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: add official website to [/currency/x] and made it editable
> Problem: [/currency/x] official website not displayed

- .meteor/packages
- .meteor/versions
Solution: Removes the es5-shim package
> Problem: es5-shim loaded into bundle #1437

- imports/ui/components/typeahead.css
- imports/ui/pages/currencyDetail/currencyDetail.scss
- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.scss
Solution: Move the add exchange field inside the exchange tab
Proposed UI
> Problem: add exchange field is in heading #1443

- imports/ui/layouts/mainLayout/mainLayout.scss
- imports/ui/pages/currencyDetail/currencyDetail.scss
- imports/ui/pages/currencyDetail/feature.html
- imports/ui/pages/currencyDetail/redflag.html
- imports/ui/pages/currencyDetail/summary.html
Solution: refined comment layout to display redflags and features properly
> Problem: comment layout is broken #1442

- imports/ui/pages/currencyDetail/currencyInfo.html
Solution: Change the helper text to No exchange available
> Problem: helper text for no exchanges in currency/:x #1449

- imports/ui/components/sideNav/sideNav.html
- imports/ui/components/sideNav/sideNav.scss
- imports/ui/layouts/mainLayout/mainLayout.html
- imports/ui/layouts/mainLayout/mainLayout.js
- imports/ui/layouts/mainLayout/mainLayout.scss
Solution: Add css for implement scrollable sidemenu and add icons as per menu names.
> Problem: side menu UX isn't very good #1417

- imports/ui/layouts/mainLayout/mainLayout.scss
Solution : Add css to handle when filter modal open.
> Problem : Not able to click on filter modal

- imports/ui/components/typeahead.js
- imports/ui/pages/compareCurrencies/compareCurrencies.js
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: corrected nx-framework component creation for noneFound. corrected cases for create events/text for when no text is provided or external button exists.
> Problem: make sure noneFound nxFramework creates if needed correct event

- imports/ui/layouts/mainLayout/mainLayout.js
- imports/ui/pages/addHashpower/addHashpower.js
Solution: Dynamically import `jquery-validate` where it's needed.
> Problem: jquery-validate is in bundle (#1440)

- imports/ui/components/sideNav/sideNav.html
solution: change icons and make layout better
> problem: side menu icons and layout is bad

- imports/ui/layouts/_bootswatch.scss
- imports/ui/layouts/_variables.scss
solution: add the scss file instead of the minified css #1461
> problem: no Blockrazor bootswatch theme

- imports/ui/pages/compareCurrencies/compareCurrencies.js
Solution: Added proper NaN checks to the values in /compareCurrency
> Problem: missing NaN checks for values in /compareCurrency #1471

- imports/ui/pages/signin/signin.html
- imports/ui/pages/signin/signin.scss
solution: fix icons to fontawesome 5 and replace bootstrap3 html5 to bootstrap4 #1470
> problem: login page has broken icons

- imports/ui/layouts/mainLayout/mainLayout.scss
Solution: Removed the left attribute of the pageHeader class
> Problem: header not aligned properly on all routes #1475

- imports/ui/components/topNav/topNav.html
Solution: Added an icon for the bounties in nav bar.
> Problem: missing icon for bounties in nav bar #1480

- imports/startup/server/fixtures.js
solution: remove fixtures for exchanges
> problem: fixtures no longer needed for exchanges

- imports/api/problems/methods.js
- imports/ui/pages/problems/newProblem.js
Solution : Fixed validation which used for check form details as per mdg:validated-method.
> Problem : new-feature form add submit without check validation.#1478

- imports/api/auctions/methods.js
Solution: Update Krazor's current price every time an auction ends.
> Problem: Krazor price is not updated (#1473)

- imports/startup/both/routes.js
solution: remove addcoin2 route from routes.js #1426
> problem: router points at addCoin2 that doesnt exist

- imports/ui/pages/auctions/newAuction.js
solution: default reserve to zero if a reserve is not provided #1488
> problem: when adding a new auction error if no reserve

- package-lock.json
- package.json
solution: upgrade bcrypt to v2.0.1 #1486
> problem:bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug

- imports/ui/pages/auctions/bidAuction.template.html
- imports/ui/pages/auctions/currencyAuction.template.html
- imports/ui/pages/problems/newProblem.html
- imports/ui/pages/problems/problem.html
- imports/ui/pages/wallet/wallet.html
solution: modify stepper on number element to include ANY decimal value #1489
> problem: cannot bid low amount on auction

- imports/ui/components/sideNav/sideNav.scss
- imports/ui/layouts/mainLayout/mainLayout.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.scss
Solution: Fixed the layout conflicts that caused horizontal scrolling and broke the responsiveness
> problem: main body is not responsive #1469

- imports/ui/pages/wallet/wallet.html
solution: use fontawesome instead of images from coins #1497
> problem:US dollar on wallets cant have an icon as its not a currency

- imports/api/coins/methods.js
Solution: Allow `currencyLogoFilename` in the `editCoin` method simple-schema.
> Problem: Cannot upload new currency logo (#1500)

- imports/api/wallet/methods.js
- imports/ui/pages/wallet/wallet.html
Solution: display kzr transactions in the [/wallet] page and updated mark as read for kzr transactions
> Problem: [/wallet] kzr transactions not shown #1477

- imports/ui/pages/wallet/wallet.js
Solution: Add validation to the input field on /wallet
> Problem: user able to add NaN to wallet on /wallet #1505

- imports/api/utilities.js
- imports/ui/components/typeahead.js
- imports/ui/pages/addCoin/addCoin.js
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: Fix the exchange creation logic so the exchange is added to the typeahead list. Add a callback function to `create` method that's called when data is created. Fix the `find` method in `LocalizableCollection`.
> Problem: Can't create exchange at [/addcoin] (#1454)

- imports/ui/pages/problems/problems.html
Solution: Add proper layout for the header of hard
> Problem: bad design of cards on /problem #1479

- imports/ui/pages/problems/newProblem.js
Solution: Solution: Add proper alerts for missing fields in the form at /new-problem
> Problem: missing proper messages for form at /new-problem #1509

- imports/ui/pages/wallet/wallet.scss
Solution: Adds overflow scroll to the table wrapper to provide a better user experience.
> Problem:table at /wallet/:x overflows viewport in mobile #1512

- imports/ui/pages/addCoin/addCoin.js
Solution: Adds a condition ro check if smartContractURL exists
> Problem: console error in /addcoin for smartContractURL #1522

- imports/api/indexDB.js
- imports/startup/client/index.js
- imports/startup/client/testingCollectionGlobals.js
- imports/ui/components/typeahead.ui-test.js
Solution: tested a bunch of things besides  created logic #1379
> Problem: typeahead untested

- imports/ui/components/loading.html
- imports/ui/components/loading.js
- imports/ui/components/loading.scss
solution: create a single loading indicator for each page where needed #1536
> problem: loading indicator offers bad UX

- imports/ui/pages/transactions/transactions.html
Solution: apply bootwatch lux theme and fix fontawesome icons #1538
> problem: transaction page not styled

- imports/ui/pages/addCoin/addCoin.html
- imports/ui/pages/addCoin/addCoin.js
Solution: Adds client side validations for required fields in the form
> Problem:missing validations on steps of form in /addCoin #1525

- imports/ui/components/topNav/topNav.html
Solution: Make the size of all icons equal in the navbar
> Problem: unequal size of icons in navbar #1543

- imports/ui/pages/addCoin/addCoin.js
solution: fixed the validation issue, when smart contract selected there is no BTCfork option, so no need to validate BTCfork, if smart contract checked
> problem: [/addcoin] TypeError: d.BTCFork is undefined #1545

- imports/ui/pages/addCoin/addCoin.js
Solution: Add the case where user inputs the algorithm
> Problem:[/addcoin] cannot proceed with new security algorithm #1552

- client/error.css
- client/error.html
Solution : Add css for page not found page.
> Problem: page not found bad UI UX #1555

- imports/api/utilities.js
- imports/ui/components/typeahead.js
- imports/ui/pages/addCoin/addCoin.js
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: strangely enough just adding add observer will sync ids created by localizable collection on server and client. #1558
> Problem: new documents can't be seen from localizable collection

- imports/ui/pages/compareCurrencies/compareCurrencies.html
solution: add bolder headers to each section #1540
> problem:compare currencies page UX is ugly

- imports/ui/pages/problems/problems.html
- imports/ui/pages/problems/problems.js
Solution: Replaced select with checkboxes in /problems
> Problem:/problems no consistency in app for selections #1554

- imports/ui/pages/addCoin/addCoin.js
Solution: Improve the validation for hashAlgorithm
> Problem: missing validation on /addCoin #1570

- imports/ui/pages/problems/problems.js
Solution: Fix the query to fetch problems
> Problem: [/problems] the searching of existing problems #1557

- imports/ui/pages/currencyDetail/currencyInfo.html
Solution: Removes d-none class from the name of currency
> Problem:/currency/:x currency name not visible in small screens #1573

- imports/api/auctions/methods.js
- imports/ui/pages/auctions/bidAuction.js
- imports/ui/pages/auctions/bidAuction.template.html
Solution: Allow users to set a maximum amount they're willing to bid and automatically place bids with small increments in their name until that maximum is reached (eBay like bidding).
> Problem: Trading auctions immediately jump to the highest bid (#1541)

- imports/api/problems/problems.js
- imports/ui/pages/problems/newProblem.js
Solution: Check whether `formattedText` actually has problem description in it before saving the problem.
> Problem: Problems can submitted without description (#1553)

- imports/ui/components/typeahead.js
Solution: add explanation as to how the props are parsed for buttons to appear.
> Problem: typeahead inline/integrated add buttons doc unclear

- imports/api/auctions/auctions.js
- imports/api/auctions/methods.js
- imports/ui/pages/auctions/currencyAuction.js
Solution: Reserve the full bid amount from user's wallet and return the difference (if it exists) when the auction ends.
> Problem: Full bid amount is not reserved from wallet (#1580, #1581)

- imports/startup/both/routes.js
solution: restrict access to [/profile] and [/profile/x] unless logged in
> problem: [/profile] can accessible without logged in #1560

- imports/ui/pages/wallet/walletTransactions.html
Solution :Use fa-times instead of fa-close
> Problem: icon not rendered properly in /wallet/:x #1576

- imports/ui/pages/userProfile/userProfile.js
Solution: check if variable initialized, before calling toFixed
> Problem: [/profile/x] exception toFixed of undefined #1559

- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.js
- imports/ui/pages/problems/problem.js
solution: replaced old font awesome cancel icon name with new one
> problem: the icon of cancel button broken everywhere #1551

- imports/ui/pages/problems/problems.html
Solution: Change the label to Problemss
> Problem: [/problems] label text of filters is incorrect #1592

- imports/api/coins/methods.js
solution: add name instead of ID in rejectedBy attribute #1583
> problem: moderator ID displayed instead of name

- imports/ui/pages/bounties/bounties.js
solution: upgrade the syntax for sweetalert #1599
> problem: shareUrl Modal is broken

- imports/ui/pages/currencyDetail/currencyInfo.js
solution: add better error catching to prevent error #1608
> problem: Exception in template helper on currencyPage

- imports/ui/pages/wallet/wallet.html
- imports/ui/pages/wallet/wallet.scss
Solution: Moved inline card icon inline style to scss file and reduced font size to 7.5em
> Problem: inconsistent size of cards on /wallet #1575

- imports/ui/pages/moderator/changedCurrencies/changedCurrencies.html
- imports/ui/pages/moderator/changedCurrencies/changedCurrencies.js
Solution: We should hide the buttons for voting on the dashboard for the changes proposed by the moderator himself.
> Problem:hide vote for changes by moderator on changes dashboard #1619

- imports/api/analytics.js
- imports/api/auctions/methods.js
- imports/ui/pages/addHashpower/addHashpower.js
- imports/ui/pages/allHashaverage/allHashaverage.js
- imports/ui/pages/allHashpower/allHashpower.js
- imports/ui/pages/auctions/allAuctions.js
- imports/ui/pages/auctions/bidAuction.js
- imports/ui/pages/editProfile/editProfile.js
solution: adding more segment.io events for testing #1622
> problem: not all pages have segment.io events

- imports/api/coins/methods.js
- imports/api/users/methods.js
- imports/ui/components/typeahead.ui-test.js
Solution: Test item creation with both external and inline create buttons.
> Problem: Typeahead create item functionality isn't tested (#1590)

- imports/ui/pages/addCoin/addCoin.html
- imports/ui/pages/addCoin/addCoin.js
- imports/ui/pages/addCoin/addCoin.scss
Solution: Adds inline errors instead of sAlert
> problem: add coin UI errors are annoying #1584

- imports/api/exchanges/methods.js
- imports/ui/components/typeahead.ui-test.js
Solution: Adapt the test to new logic on `/addcoin` page.
> Problem: Test broken in #1627

- imports/ui/components/typeahead.ui-test.js
Solution: Test whether inline button reacts to events if an external-integrated button exists.
> Problem: Inline/external-integrated button dynamics not tested. (#1589)

- imports/ui/components/typeahead.ui-test.js
Solution: Test whether an externally created item is added to typeahead's search results when transcient option is on.
> Problem: Typeahead transcient prop not tested. (#1587)

- imports/startup/both/routes.js
- imports/ui/pages/moderator/pardon/pardon.html
- imports/ui/pages/moderator/pardon/pardon.js
- imports/ui/pages/moderator/pardon/pardonUser.html
- imports/ui/pages/moderator/pardon/pardonUser.js
Solution: displaying pardon request one at a time. Bootswatchified
suspended users page
> Problem: Suspended users bad UI/UX #1277

- imports/ui/pages/signup/signup.html
- imports/ui/pages/signup/signup.js
Solution: Adds proper styling to signup page
> Problem: [/signup] Broken styles on sign up form #1634

- imports/ui/pages/moderator/appLogs/appLogs.html
- imports/ui/pages/moderator/appLogs/appLogs.js
Solution: Implemeneted a consistent filter menu and wrapped content in card element
> Problem: [/moderator/applogs] bad UI/UX #1644

- imports/ui/pages/moderator/questions/questions.js
Solution: Adds a validation to the input field in /moderator/questions
> Problem: moderator is able to create an empty question #1643

- imports/startup/both/routes.js
- imports/ui/pages/moderator/flagged/flagged.html
- imports/ui/pages/moderator/flagged/flagged.js
- imports/ui/pages/moderator/flagged/flaggedItem.html
- imports/ui/pages/moderator/flagged/flaggedItem.js
Solution: Created dynamic route supporting different collection items. Displaying one flagged item at item and Bootswatchified the page
> Problem: [/moderator/flagged] Bad UI/UX #1278

- client/userHover.js
- imports/api/users/server/publications.js
- imports/startup/both/routes.js
- imports/ui/pages/userProfile/userProfile.js
Solution: Added UserData subscription;  fetching userData by user object stored in userProfile template instance.
> Problem: [/profile/:slug] Wrong kzr balance #1654

- imports/ui/pages/transactions/transactions.html
Solution: Applied the same icon used in wallet to the transaction page reset button
> Problem: Inconsistent icons in txns & wallet #1640

- imports/ui/pages/wallet/wallet.js
Solution: Use the message attribue to get the notification count
> Problem:No notification on /wallet after completing bounty #1637

- imports/api/coins/currencies.js
- imports/api/coins/methods.js
- imports/ui/pages/addCoin/addCoin.html
- imports/ui/pages/addCoin/addCoin.js
Solution: Dynamically validate each step of the wizard in order to see if it matches the predefined schema.
> problem: [/addcoin] Users not conveniently informed of errors (#1549)

- imports/ui/pages/transactions/transactions.html
- imports/ui/pages/transactions/transactions.js
Solution: Made the design consistent to other filter menus
> Problem: inconsistent design of filter in /transaction/x #1658

- imports/ui/pages/wallet/walletTransactions.html
- imports/ui/pages/wallet/walletTransactions.js
Solution: Made the design of the menu consistent with other filter menus.
> Problem: inconsistent design of filter menu in /wallet/x #1659

- imports/ui/pages/signin/twoFactor.html
- imports/ui/pages/signin/twoFactor.js
Solution: Added a cancel button which terminates the user's session and redirects to home
> Problem: cannot cancel 2FA login #1663

- imports/ui/components/typeNX.js
- imports/ui/components/typeahead.ui-test.js
Solution: Check if `history.state` is defined before using it.
> Problem: Uncaught TypeError: Cannot read property 'params' of null (#1629)

- imports/api/coins/currencies.js
- imports/api/coins/methods.js
- imports/ui/pages/addCoin/addCoin.html
solution: conditionally validate the smartContractURL field based on the checkbox in step 1 of addCoin #1612
> problem: smart contract isnt validated for /addCoin

- imports/api/utilities.js
- imports/ui/components/global/globalHelpers.js
- imports/ui/components/sideNav/sideNav.html
- imports/ui/components/sideNav/sideNav.js
- imports/ui/components/topNav/topNav.html
- imports/ui/components/topNav/topNav.js
- imports/ui/pages/wallet/wallet.scss
Solution: properly formatting balance amount before upsert. introduced global helper to format balance amount for both topNav and sideNav
> Problem: wrong format for topNav kzr balance #1671

- imports/ui/pages/moderator/flaggedUsers/flaggedUsers.html
Solution: applied .table-light css class to table rows.
> Problem: [/moderator/flagged-users] Bad UI-UX #1683

- imports/ui/pages/moderator/appLogs/appLogs.html
- imports/ui/pages/moderator/candidates/candidates.html
- imports/ui/pages/moderator/changedCurrencies/changedCurrencies.html
- imports/ui/pages/moderator/changedCurrencies/changedCurrency.html
- imports/ui/pages/moderator/exchanges/removeExchanges.html
- imports/ui/pages/moderator/flagged/flagged.html
- imports/ui/pages/moderator/flagged/flaggedItem.html
- imports/ui/pages/moderator/flaggedUsers/flaggedIP.html
- imports/ui/pages/moderator/hashpower/flaggedHashpower.html
- imports/ui/pages/moderator/moderatorDash/moderatorDash.html
- imports/ui/pages/moderator/pardon/pardon.html
- imports/ui/pages/moderator/problems/solvedProblems.html
- imports/ui/pages/moderator/questions/questions.html
Solution: applied pageHeader and pageTitle styles to all admin page headers
> Problem: inconsistent admin page header UI #1689

- imports/api/problems/methods.js
- imports/api/problems/problems.js
- imports/ui/pages/problems/newProblem.js
Solution: Remove validation when adding new problems in development environment.
> Problem: Add problem requires validation on dev (#1566)

- imports/ui/components/topNav/topNav.scss
- imports/ui/layouts/mainLayout/mainLayout.scss
- imports/ui/pages/addCoin/addCoin.html
- imports/ui/pages/auctions/allAuctions.template.html
- imports/ui/pages/problems/problems.html
Solution: Fixes misaligned layouts in the application
> Problem:Bad ui in some places after switching to full bootswatch #1680

- imports/api/users/server/publications.js
- imports/api/users/server/startup.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
Solution: Prevent possible data corruption in the future in order to prevent weird results.
> Problem: [/] Users online is always 0 (#1651)

- imports/ui/pages/currencyDetail/currencyDetail.js
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: Fix the way `_id` property of an exchange is stored when an exchange is appended to a currency.
> Problem: Error with Litecoin detail page (#1700)

- client/main.css
- imports/ui/layouts/mainLayout/mainLayout.scss
Solution: remove incorrect modal styles and left-aligned the text
> Problem: misaligned modals in the application #1702

- imports/api/coins/methods.js
- imports/api/localizableCollection.test.js
- imports/api/localizableCollection.ui-test.js
Solution: Write unit tests and UI tests to completely test out localizable collection.
> Problem: Localizable collection untested (#1515)

- imports/startup/client/config.js
- imports/startup/client/index.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
- imports/ui/shared/header/header.js
- imports/ui/shared/sidebar/sidebar.scss
solution: dynamically adding sidebar responsive classes according to the device width
> problem: menu is not functioning correctly #1712

- imports/api/features/methods.js
Solution: Adds validation for the feature
> Problem: user is able to create empty features in /currency/:x #1725

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.scss
- public/images/logo_black.svg
Solution: display brand logo instead of text, for small screens and Left aligned 'Blockrazor' text for medium screens.
> Problem: Brand text conflict with username #1716

- imports/ui/pages/bounties/bounties.html
- imports/ui/pages/bounties/bounties.scss
Solution: correct the placement of button in the page
> Problem: [/bounties] Share button misplaced #1717

- imports/ui/pages/addCoin/smart.wizard.custom.css
Solution: make text color white as the background is dark
> Problem: [/addCoin] active header not distinguishable #1720

- imports/ui/pages/moderator/changedCurrencies/changedCurrencies.js
- imports/ui/pages/moderator/changedCurrencies/changedCurrency.js
Solution: removed un-needed broken links which avoided page load
> Problem: [/moderator/changedCurrencies/] console error #1730

- imports/ui/pages/exchanges/exchanges.html
- imports/ui/pages/exchanges/exchanges.scss
Solution: refined the UI and removed unwanted styles
> Problem: [/exchanges] large gap at top #1724

- imports/ui/components/typeahead.ui-test.js
- imports/ui/stylesheets/bundle.scss
- package-lock.json
- package.json
Solution: Fix client-side test failures caused by UI changes.
> Problem: Tests are failing (#1734)

- imports/ui/shared/sidebar/sidebar.scss
Solution: Changes the font color of the sub menu
> Problem: krazor menu items are not visible on side menu #1714

- imports/ui/shared/header/header.html
Solution: makes the size of icons equal
> Problem: unequal size of icons in header #1723

- imports/api/problems/problems.js
- imports/ui/pages/problems/newProblem.html
- imports/ui/pages/problems/newProblem.js
Solution: Shows inline error messages
> Problem: [/new-problem] validation errors not shown #1722

- imports/ui/pages/signin/signin.scss
Solution: change font color of link and font size #1742
> Problem: [/sign up] Sign in link on isn't seen

- imports/api/utilities.js
- imports/ui/components/global/globalHelpers.js
- imports/ui/components/sideNav/sideNav.html
- imports/ui/components/sideNav/sideNav.js
- imports/ui/components/topNav/topNav.html
- imports/ui/components/topNav/topNav.js
- imports/ui/pages/userProfile/userProfile.js
- imports/ui/pages/wallet/wallet.js
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
- imports/ui/shared/sidebar/sidebar.html
- imports/ui/shared/sidebar/sidebar.js
Solution: Reversed changes made by #1675. add if statement checking whether balance is of type string
> Problem: Most of the codebase expects user balance to be numerical #1694

- imports/ui/pages/problems/newProblem.js
Solution: parsing balance value to float if its of type string
> Problem: [/new-problem] krazor balance not being displayed #1750

- imports/api/problems/methods.js
Solution: Unsetting the non-numerical balance and updating it with a numerical one.
> Problem: [/new-problem] cannot create a new problem #1753

- imports/ui/shared/footer/footer.html
- imports/ui/shared/footer/footer.scss
solution: footer had incorrect and missing class names #1747
> Problem : Footer has too much black space

- imports/ui/layouts/layout.scss
- imports/ui/shared/header/header.html
Solution: added link to faq section with icon. updated wallet and bounty icons
> Problem: missing link to faq section on header #1749

- imports/ui/shared/header/header.html
Solution: Fix client-side test failures caused by UI changes.
> Problem: Tests are failing

- imports/api/activityLog/methods.js
- imports/api/problems/methods.js
- imports/ui/pages/activityLog/activityLog.js
- imports/ui/shared/sidebar/sidebar.html
- imports/ui/shared/sidebar/sidebar.js
Solution: Show problem related notifications count beside the `Get Help` sidebar link.
> Problem: No way to notify user of assigned problem (#1760)

- imports/ui/shared/footer/footer.html
Solution: Remove CoreUI context completely and add Blockrazor related footer text.
> Problem: Footer contains core UI context instead of blockrazor (#1756)

- AUTHORS
- imports/ui/pages/currencyDetail/currency.scss
- imports/ui/pages/wallet/wallet.scss
Solution: Fixed Some paddings and highlighted Total balance. Also fixed the drobdown currency selector
> Problem: Small UI improvements required in the wallet page #1765

- imports/ui/pages/problems/problems.html
- imports/ui/pages/problems/problems.js
Solution: use different badge colors for problems and questions
> Problem: same color used for all help badges #1757

- imports/ui/pages/currencyDetail/currency.scss
- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/shared/sidebar/sidebar.html
Solution: Fixed Home ui by changing color to input. Positioing the search results and fixed the add ICO button. Also Fixed the share button icon not displaying and misalignment.
> Problem: Need to fix UI in the Home page and In the SideBar #1772

- imports/ui/pages/currencyDetail/currency.scss
- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
> [UI-UX] Currency container & card layout fix #1774 & #1776

- imports/ui/layouts/layout.html
- imports/ui/shared/footer/footer.html
- imports/ui/shared/footer/footer.scss
- imports/ui/stylesheets/common.scss
Solution : Layout fixed, moved inside <main>
> Problem : Footer Layout need to be fix #1778

- imports/ui/shared/header/header.html
- imports/ui/shared/sidebar/sidebar.html
- imports/ui/stylesheets/common.scss
Solution #1780 & #1781 :
- Remove duplicate items
- Hide FAQs link on mobile & add to side nav
- Hide Bounties on mobile screen
> Problem : Duplicate menu on top nav and mobile layout broken

- imports/ui/pages/wallet/wallet.scss
Solution: Reduce the img size to 100px
>  Problem: Messed up wallet page cards #1784

- imports/ui/pages/returnedCurrencies/currency.html
solution: add dollar sign and display 0.00 if null #1748
> problem:price has no currency and sometimes blank

- imports/ui/shared/footer/footer.html
Solution: adds missing spaces in the footer text
> Problem: missing spaces in footer text #1790

- imports/ui/shared/header/header.html
Solution: there should be only one icon for notification of bounties in the header
> Problem: multiple notifiers for bounties in header #1792

- imports/ui/pages/ratings/currencyChoice.html
- imports/ui/pages/ratings/currencyChoices.html
- imports/ui/pages/ratings/ratings.scss
Solution: Updated ratings UI. Elimnated unnecessary styles
> Problem: [/ratings] bad UI/UX on ratings page #1743

- imports/api/utilities.js
Solution: Add import {Meteor} from "meteor/meteor" at the top
>  Problem: Meteor undefined in imports/api/utilities.js file #1788

- .meteor/versions
- imports/ui/shared/sidebar/sidebar.html
solution: tidy up non authenticated users menu #1799
> problem: menu is ugly

- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
solution: add search bar to header #1795
> problem: search bar is not obvious

- client/main.css
- imports/startup/both/routes.js
- imports/ui/layouts/layout.html
- imports/ui/layouts/layout.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
solution: moved the filter button into the new header to make it more obvious #1805
> problem: filter UX on homepage was bad

- .travis.yml
- imports/api/auctions/methods.js
- imports/ui/pages/auctions/currencyAuction.js
- imports/ui/pages/auctions/currencyAuction.template.html
Solution: Add inline bootstrap validation and fix the form.
> Problem: Auction form not working in /currencyAuction (#1759)

- imports/api/localizableCollection.test.js
solution: updated test to expect at least 1 not be equal to 1 #1810
> problem: scripts broken with new landing page

- imports/ui/layouts/layout.scss
solution: add /static instead of images on landing page image #1808
> problem: homepage image not loading

- imports/ui/pages/returnedCurrencies/homepage.ui-test.js
Solution: Fix broken client-side tests.
> Problem: Tests are broken (#1812)

- imports/ui/layouts/layout.scss
Solution: Maybe instead of increasing font size abruptly, scale the icon to animate smoothly.
> Problem: Homepage animations still not smooth enough #1816

- docs/TRANSLATIONS.md
solution: add @anbud's short guide
> problem: no document explaining how to add translations

- i18n/bounties.en.i18n.json
- imports/ui/pages/bounties/bounties.html
- imports/ui/pages/bounties/bounties.js
- imports/ui/pages/bounties/bountyRender.html
- imports/ui/pages/bounties/bountyRender.js
Solution: Convert templates from literal strings to TAPi18n translation keys.
> Problem: Bounties are not multilingual (#1831)

- i18n/hashpower.en.i18n.json
- imports/ui/pages/addHashpower/addHashpower.html
- imports/ui/pages/addHashpower/addHashpower.js
- imports/ui/pages/allHashaverage/allHashaverage.html
- imports/ui/pages/allHashaverage/allHashaverage.js
- imports/ui/pages/allHashpower/allHashpower.html
- imports/ui/pages/allHashpower/allHashpower.js
Solution: Convert templates from literal strings to TAPi18n translation keys.
> Problem: Hashpower related pages are not multilingual (#1833)

- i18n/user.en.i18n.json
- imports/ui/pages/editProfile/editProfile.html
- imports/ui/pages/editProfile/editProfile.js
- imports/ui/pages/signin/signin.html
- imports/ui/pages/signin/twoFactor.html
- imports/ui/pages/signup/signup.html
- imports/ui/pages/signup/signup.js
- imports/ui/pages/userPendingCurrencies/userPendingBounty.html
- imports/ui/pages/userPendingCurrencies/userPendingBounty.js
- imports/ui/pages/userPendingCurrencies/userPendingCurrencies.html
- imports/ui/pages/userPendingCurrencies/userPendingCurrency.html
- imports/ui/pages/userProfile/userProfile.html
- imports/ui/pages/userProfile/userProfile.js
Solution: Convert templates from literal strings to TAPi18n translation keys.
> Problem: User related pages are not multilingual (#1837)

- imports/ui/pages/landingpage/landingpage.html
Solution : Update link to /login from /signin
> Problem : Broken link for get started #1846

- imports/ui/layouts/layout.scss
Solution : Extra margin removed from css
> Problem : Home page horizontal scroll issue #1849

- imports/ui/pages/wallet/wallet.js
Solution : Currency formatted for balance display in wallet page.
> Problem : Currency amount is not formatted #1848

- README.md
problem: blockrazorbot is now called emurgobot but readme still says blockrazorbot
solution: update readme to reflect new changes
> problem: blockrazorbot is now called emurgobot

- .meteor/packages
- imports/startup/both/routes.js
- imports/ui/pages/signin/signin.html
- imports/ui/pages/signin/signin.js
- server/main.js
**Solution :**
- Password reset template added
- Email setup to send password reset link
**Sendgrid  Details**
Username : blockrazor
Password : blockrazor123
>  Problem : No reset password option #1857

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
solution: overhaul the mobile ui components to make them pretty #1860
> problem: UI on mobile is broken

- imports/ui/shared/sidebar/sidebar.js
solution: only close the menu on mobile devices desktop it will stay open #1863
> problem: menu does not close when clicked on mobile

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
solution: add a modal if the users language is NOT english, do not prompt again if they change the language #1861
> problem: bad UX for language choice/selection

- imports/ui/pages/editProfile/editProfile.html
- imports/ui/pages/editProfile/editProfile.js
solution: Solution: Set validation on the username object when editing a profile.
> problem: can set username as null

- client/userHover.html
- imports/ui/pages/currencyDetail/commentRender.html
- imports/ui/pages/currencyDetail/feature.html
- imports/ui/pages/currencyDetail/redflag.html
- imports/ui/pages/currencyDetail/redflagComment.html
solution: made them look really pretty #1871
> problem: chat containers have bad UX

- imports/ui/pages/bounties/bounties.scss
- package-lock.json
Solution: add margin between header & share button
> Problem: share button overlaps with header on bounties page #1874

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
Solution: fixes the modal by adding default language
> Problem:language modal pops up if current language is selected #1876

- i18n/user.en.i18n.json
- imports/ui/pages/signin/signin.html
- imports/ui/pages/signin/signin.js
Solution: Convert literal strings to TAPi18n keys.
> Problem: Reset password page is not multilingual (#1878)

- imports/startup/both/routes.js
- imports/ui/pages/landingpage/landingpage.html
- imports/ui/pages/landingpage/landingpage.js
- imports/ui/shared/sidebar/sidebar.html
Solution : 
- Landing and home pages moved to separate routes
- Changed all `/` navigation to `/home` for new home route
>  Problem : Not logged-in user problems #1859

- .meteor/packages
- .meteor/versions
- server/kadira.js
Solution: Connect Blockrazor to our Kadira instance
> Problem: Bad performance with site (#1873)

- .eslintrc.yml
- package-lock.json
- package.json
Solution : eslint meteor plugin added
> Problem : Eslint not configured for meteor #1882

- imports/ui/layouts/layout.scss
- imports/ui/pages/landingpage/landingpage.html
- imports/ui/pages/landingpage/landingpage.js
- imports/ui/pages/landingpage/landingpage.scss
Solution :
1. Layout changed for intro banner
2. Signup form added in home banner
3. More Features added
4. Welcome card added with useful links for logged-in users
> Problem : Landing page content (UI-UX) #1854

- imports/ui/shared/header/header.js
solution: redirect to home route #1893
> problem: search does not work when not authenticated

- imports/ui/pages/signup/signup.html
solution: enforce password lenght on login and ensure email is email #1895
> problem: zero password strength enforced on signup

- client/main.css
- imports/ui/pages/currencyDetail/discussion.html
- imports/ui/pages/currencyDetail/features.html
- imports/ui/pages/currencyDetail/redflags.html
- imports/ui/pages/currencyDetail/summaries.html
solution: force scrollbars to show to offer better UX #1897
> problem: scroll bars are invisible

- imports/ui/pages/currencyDetail/currencyDetail.scss
- imports/ui/pages/currencyDetail/summaries.html
solution: clean up the UX and make it nice #1898
> Remaining chars display has bad ux

- imports/ui/pages/codebase/codebase.js
- imports/ui/pages/communities/commQuestions.js
- imports/ui/pages/currencyDetail/currencyInfo.js
- imports/ui/pages/currencyDetail/walletimages.js
- imports/ui/pages/ratings/question.js
- imports/ui/pages/wallet/wallet.js
Solution: Fix the event handler that was causing not found images to constantly reload.
> Problem: Images are constantly reloading (#1886)

- imports/ui/pages/compareCurrencies/compareCurrencies.html
solution: allow the header of the currency drill down into the currency to view it #1905
> problem: cannot select currency when comparing

- imports/startup/both/routes.js
- imports/ui/pages/landingpage/landingpage.js
Solution : breadcrumb value added back for landing page and breadcrumb show on landing page destroyed
> Problem: property 'split' of undefined #1908

- imports/ui/pages/problems/problemComments.html
- imports/ui/pages/problems/problemComments.js
- imports/ui/pages/problems/problems.scss
Solution : 
1. Input type text replaced with text area
2. Text limit msg alignment updated
3. Alignments updated for help icon (modal)
> Problem : Comments ux is bad in /problem #1912

- i18n/shared.en.i18n.json
- i18n/shared.sr.i18n.json
- imports/ui/shared/sidebar/sidebar.html
Solution : Link added on sidenav
_PS : Many changes are due to eslint, mostly alignments updated._
>  Problem : FAQ link not on Navigation #1915

- imports/ui/pages/allHashaverage/allHashaverage.html
Solution: applied CoreUI styles to the page
> Problem: [/avg-hashpower] bad UI-UX #1918

- imports/ui/pages/allHashpower/allHashpower.html
solution: cleaned up UI, added Core UI styling
> problem: [/hashpower] bad UI-UX #1844

- .gitignore
- .meteor/packages
- .meteor/versions
- README.md
- server/main.js
- settings.json
Solution : 
1. Email settings moved to `settings.json`
2. `Readme` updated for meteor settings
3. `settings.json` added to `.gitignore`
> Problem : Email password is in code #1921

- i18n/shared.en.i18n.json
- i18n/shared.sr.i18n.json
- imports/ui/shared/sidebar/sidebar.html
- imports/ui/shared/sidebar/sidebar.js
Solution: Adds a link in the side menu to access the developer route if the user is developer
> Problem: no link to visit /developers route #1927

- imports/startup/both/routes.js
- imports/ui/pages/moderator/hashpower/flaggedHashpower.html
- imports/ui/pages/moderator/hashpower/flaggedHashpowers.html
- imports/ui/pages/moderator/hashpower/flaggedHashpowers.js
Solution: added CoreUi styles to the page. Moderator can only review one flagged hashpower at a time
> Problem: [/flagged-hashpower] bad UI-UX #1920

- imports/ui/pages/moderator/appLogs/appLogs.html
> Problem: [/moderator/applogs] Bad UI-UX #1922

- imports/ui/pages/moderator/flaggedUsers/flaggedIP.html
- imports/ui/pages/moderator/flaggedUsers/flaggedUsers.html
Solution: cleaned up pages; applied core-ui styling
> Problem: [/flagged-ip/:address] bad UI-UX #1934

- imports/ui/pages/prices/priceChart.html
Solution: Improved UI. Put chart canvas inside a card element
> Problem: [/priceChart] bad UI-UX #1936

- imports/ui/pages/transactions/transactions.html
- imports/ui/pages/transactions/transactions.js
Solution: Add CoreUI styles to page. Highlighting current page in pagination element
> Problem: [/transactions/1] bad ui-ux #1938

- imports/ui/pages/wallet/walletTransactions.html
- imports/ui/stylesheets/common.scss
Solution: Clean up UI. Added custom style for .reactiveTable thead element.
> Problem: [/wallet/:currency] bad UI-UX #1940

- imports/ui/pages/addHashpower/addHashpower.html
Solution: cleaned up ui, eliminated large margins
> Problem: [/add-hashpower] bad UI-UX #1932

- client/main.css
- imports/ui/shared/footer/footer.scss
solution: footer was using a fixed height and causing two scrollbars to apear #1929
> problem: weird scroll length on mobile

- i18n/home.en.i18n.json
- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
solution: add a new stats element on home page #1797
> problem: bad UX on user activity attributes

- imports/startup/both/routes.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
solution: redirect to landing when not logged in and homepage when you are #1943
> problem: existing users are directed to landing page instead of home

- imports/startup/both/routes.js
- imports/ui/layouts/layout.js
- imports/ui/stylesheets/common.scss
solution: added param to breadcrumb option, appending param to breadcrumb text if it exists
> problem: breadcrumbs do not show what currency you are looking at #1950

- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
solution: displaying total number of online users as fraction of total registered users.
> problem: total registered users not shown #1951

- imports/ui/layouts/layout.js
- imports/ui/pages/wallet/walletTransactions.js
Solution: checking whether i (text) is defined
> Problem: [/wallet/kzr] TypeError thrown in console #1954

- i18n/home.en.i18n.json
- imports/ui/pages/landingpage/landingpage.html
Solution: Convert literal strings in the landing page template to TAPi18n.
> Problem: Landing page isn't using tap18 translation (#1942)

- i18n/home.en.i18n.json
> problem: incorrect English

- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
solution: user the userStats collection instead of a reactive count #1959
> problem: incorrect number of total users

- i18n/home.en.i18n.json
- imports/api/users/methods.js
- imports/api/users/server/startup.js
- imports/ui/pages/landingpage/landingpage.html
- imports/ui/pages/landingpage/landingpage.js
Solution: Add site metrics to the landing page (active + total users, signups this month, comments in the last month)
> Problem: People might think blockrazor is inactive (#1964)

- imports/api/coins/methods.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
Solution: Fix total currencies count.
> Problem: Total currencies is incorrect (#1963)

- i18n/breadcrumbs.en.i18n.json
- i18n/deadman.en.i18n.json
- i18n/shared.en.i18n.json
- imports/api/encryption/encryption.js
- imports/api/encryption/methods.js
- imports/api/encryption/methods.test.js
- imports/api/encryption/server/publications.js
- imports/api/encryption/server/startup.js
- imports/api/indexDB.js
- imports/startup/both/index.js
- imports/startup/both/routes.js
- imports/startup/server/index.js
- imports/ui/pages/deadmanVote/deadmanVote.html
- imports/ui/pages/deadmanVote/deadmanVote.js
- imports/ui/pages/landingpage/landingpage.js
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
Solution: A deadman switch triggers a mongo insert with the decryption key (insert into `encryption` collection). If a decryption key is found in the database, a vote is initiated allowing the community (top 90% of KZR holders) to vote for who the keys should go to.
> Problem: Some data cannot be public (#1968)

- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
Solution : Display search stats only when search is active
> Problem: search stats displayed always #1946

- README.md
- server/main.js
Solution :
- Email URL issue fixed
- Email setup instructions added on README
Fixed for #1967
> Problem: forget password email not working

- imports/ui/pages/moderator/flaggedUsers/flaggedUsers.js
Solution: Sort flagged users by last access time.
> Problem: Flagged users not sorted by time (#1979)

- imports/ui/pages/moderator/changedCurrencies/changedCurrencies.js
- imports/ui/pages/moderator/changedCurrencies/changedCurrency.js
solution: checking voteMetrics if user already voted. Only fetch changes where user isn't found in voteMetrics
> problem: user shown already voted on change #1984

- imports/ui/components/compatability/bootstrap3-editable/js/bootstrap-editable.js
- imports/ui/components/global/globalHelpers.js
- imports/ui/components/sideNav/sideNav.html
- imports/ui/pages/addCoin/addCoin.html
- imports/ui/shared/sidebar/sidebar.html
solution: bounties link navigates directly to active bounty page. added ability to cancel new currency bounty
> problem: users can't easily navigate to bounty in-progress #1987

- i18n/home.en.i18n.json
- i18n/user.en.i18n.json
- imports/ui/pages/landingpage/landingpage.html
- imports/ui/pages/landingpage/landingpage.js
- imports/ui/pages/landingpage/landingpage.scss
- imports/ui/pages/signin/signin.js
- imports/ui/shared/header/header.html
Solution: Adds signin with facebook & github to homepage. Removes signin button from header
> problem: extra steps required for facebook/github signup #1990

- imports/ui/layouts/layout.html
- imports/ui/layouts/layout.scss
- imports/ui/shared/footer/footer.scss
- imports/ui/stylesheets/common.scss
Solution : Footer moved out of main container and CSS updated for extra scrollbar
>  Problem: bottom of page content is cut off #1986

- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
solution: put site stats in colored cards with icons making them more conspicuos.
> problem: site stats on landing page are easy to miss #1991

- i18n/shared.en.i18n.json
- i18n/shared.sr.i18n.json
- imports/ui/shared/footer/footer.html
- imports/ui/shared/footer/footer.js
- imports/ui/shared/footer/footer.scss
Solution : Language change options added on footer
>  Problem: difficult to change language #1993

- client/main.css
Solution : CSS fixed by removing y-scroll
> Problem: weird right side border #1982

- i18n/moderator.en.i18n.json
- imports/api/users/users.js
- imports/ui/pages/moderator/flaggedUsers/flaggedUsers.html
- imports/ui/pages/moderator/flaggedUsers/flaggedUsers.js
Solution: Add a new data point, last time this IP was used. Add a sorting dropbox above the data table.
> Problem: Can't sort suspicious IP's by IP login time (#1983)

- imports/ui/shared/header/header.html
Solution: Uses red color for all notification counts
> Problem:Inconsistent colors used in header for notifying user #2005

- imports/api/developers/methods.js
Solution: user cann't apply as a developer is the previous application is not processed
> Problem: user can apply for developer even if decision is pending #2007

- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.scss
Solution : UI-UX updated for button
We need about auction content [in FAQs maybe] - then link to learn more ...
> Problem: auction box doesn't really fit in #1992

- imports/ui/pages/signin/signin.js
Solution : Redirect user to /home on login
> Problem: on sign in, users in landing page #2009

- auctions.de.i18n.json
- messages.sr.i18n.json
Solution: Translate auctions (Српски језик,  Deutsch), messages (Српски језик).
> Problem: Blockrazor strings are not translated

- i18n/breadcrumbs.en.i18n.json
- i18n/moderator.en.i18n.json
- imports/api/indexDB.js
- imports/api/translations/methods.js
- imports/api/translations/server/publications.js
- imports/api/translations/server/startup.js
- imports/api/translations/translations.js
- imports/startup/both/routes.js
- imports/startup/server/index.js
- imports/ui/pages/moderator/translations/translation.html
- imports/ui/pages/moderator/translations/translation.js
- imports/ui/pages/moderator/translations/translations.html
- imports/ui/pages/moderator/translations/translations.js
- imports/ui/pages/translations/translations.js
- imports/ui/shared/sidebar/sidebar.html
- package-lock.json
- package.json
Solution: Instead of saving translations directly back to the filesystem, save them in a collection, let moderators approve all translations and send a PR with new and approved translations every day.
> Problem: It's difficult for non-tech people to add translations (#1994)

- imports/ui/pages/moderator/hashpower/flaggedHashpower.js
- imports/ui/pages/moderator/hashpower/flaggedHashpowers.html
- imports/ui/pages/moderator/hashpower/flaggedHashpowers.js
- imports/ui/pages/signin/signin.html
solution: only displaying flagged hashpower where mod hasn't voted yet
> problem: [flagged-haspower] mod still see items already voted on #2027

- imports/startup/both/routes.js
- imports/ui/pages/signin/login.html
- imports/ui/pages/signin/login.js
- imports/ui/pages/signin/signin.html
solution: fixed login UI. centered login card
> problem: [/login] bad UI/UX #2028

- imports/ui/pages/currencyDetail/currencyDetail.scss
- imports/ui/pages/currencyDetail/currencyInfo.scss
- imports/ui/pages/currencyDetail/fundamentalMetrics.html
- package-lock.json
Solution : Layout updated to fix inconsistent ui for graphs
> Problem: inconsistent UI in /currency #1926

- imports/startup/both/routes.js
- imports/ui/pages/signin/signin.html
- imports/ui/pages/signin/signin.scss
Solution : Signin page made like earlier before
Fixes for #2036 and #2034
> Problem : /login page UI-UX broken #2036

- imports/ui/pages/editProfile/editProfile.html
- imports/ui/pages/editProfile/editProfile.js
- imports/ui/pages/userProfile/userProfile.html
- imports/ui/pages/userProfile/userProfile.js
Solution: Add an upload image button under the profile picture and remove it from edit profile tab.
> Problem: Uploading a new profile picture is annoying (#2039)

- imports/api/wallet/methods.js
- imports/ui/pages/wallet/wallet.html
- imports/ui/pages/wallet/wallet.js
- imports/ui/shared/sidebar/sidebar.js
Solution : Welcome notification updated on wallet initialization, welcome notification added in wallet ui and in sidebar
> Problem : No welcome wallet notification #2041

- imports/ui/pages/wallet/wallet.scss
- imports/ui/pages/wallet/walletTransactions.html
- imports/ui/pages/wallet/walletTransactions.js
Solution : Filter options layout updated, extra navigation removed, table horizontal scroll bar removed
Value for Wallet date and time fixed
>  Problem : Wallet transaction has bad UI-UX #2045

- imports/ui/pages/bounties/bounties.html
- imports/ui/pages/bounties/bounties.scss
Solution : Filter options layout and UI updated and Share with friends CTA broken UI fixed
>  Problem : Filter bounties UI is broken #2048

- imports/ui/layouts/layout.scss
- imports/ui/pages/signin/login.html
- imports/ui/pages/signin/signin.html
- imports/ui/pages/signup/signup.html
Solution: added the Project name on the above of login, signup and reset cards with the home page link.
> Problem: login, reset-password and signup page should have home #2047

- README.md
Solution : Contribution guide updated for updating issue after PR
> Problem : Guide on Readme needs update #2052

- AUTHORS
- imports/ui/pages/problems/problems.html
- imports/ui/pages/problems/problems.js
- imports/ui/pages/problems/problems.scss
Solution: Modified how the filter UI is styled on /problems to make it more in line with /bounties
> Problem: [/problems] Filter UI is broken #2057

- imports/ui/pages/signin/signin.js
Solution: Redirect all login methods to `/home` after login.
> Problem: Users not always redirected to home route after login (#2050)

- imports/ui/shared/sidebar/sidebar.html
Solution: Open website in new tab
> Problem: Krazor Home link doesn't open in a new tab

- .meteor/packages
- .meteor/versions
- client/root.html
- package-lock.json
- server/server.routes.js
Solution:  Implement SEO on key pages to ensure BR can be index and crawled. #2053
> Problem: site cant be indexed by search engines

- imports/ui/pages/auctions/currencyAuction.js
- imports/ui/pages/auctions/currencyAuction.template.html
solution : set maximum character length.
> problem:Amount textbox don't have maximum character limit

- imports/ui/pages/addCoin/addCoin.html
- imports/ui/pages/addCoin/addCoin.js
- imports/ui/pages/auctions/bidAuction.js
- imports/ui/pages/auctions/bidAuction.template.html
- imports/ui/pages/wallet/wallet.html
- imports/ui/pages/wallet/wallet.js
Solution:Set maximum character length
> Problem:Amount input text field don't have maximum limit

- imports/ui/pages/bounties/bounties.html
- imports/ui/pages/bounties/bounties.scss
Solution : span class removed which was hidding the button because of libraries we have used
> Problem : Share with friends btn not visible #2066

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
Solution : Redirect to login page after logout
> Problem :- Redirect to 404 page when click on logout button

- package-lock.json
- package.json
- server/server.routes.js
Solution: Use puppeteer to render pages on the server and serve them to bots. Implement this approach on a few SEO critical pages. To optimize the content delivery to bots, implement a simple caching mechanism.
> Problem: Currency pages are not indexable (#2071)

- imports/ui/pages/signup/signup.html
solution: allow passwords of 6+ chars instead of limiting it to 6
> problem: password validation requies exactly 6 chars

- imports/startup/client/config.js
- package-lock.json
Solution: remove the incorrect onclick event
> Problem: mobile side-bar cannot navigate

- imports/api/coins/methods.js
- imports/api/indexDB.js
- imports/api/users/server/publications.js
- imports/api/users/userLikedCoin.js
Solution: Added a new collection with user perference per user
> Problem: Cannot easily get Like/Dislike Coin per User

- AUTHORS
- imports/api/coins/coinPerf.js
- imports/api/coins/methods.js
- imports/api/users/userLikedCoin.js
Solution: add simple schema and modify the method
> Problem: not using simple schema on coinPerf and userPerf

- .gitignore
- imports/api/features/methods.js
Solution: wrap newFeature into meteor.method
> Problem: newFeature doesnt work for mobile
