Blockrazor/blockrazor

- client/users/addCoin.js
- server/serverdb/addCoin.js
- views/templates/users/addCoin.html
Solution: check both the approved and pending databases to see if the currency name the user is typing in is already in the database and tell them immediatly before filling in the rest of the form and getting irritated later
Fixes #7
> Problem: user may try to add existing currency

- client/users/ratings/ratings.js
- server/methods/imageUpload.js
- views/templates/moderators/approveWalletImage.html
solution: return success and error messages to user using sAlert #82. File type extensions are now detected via the mime-type and not hardcoded to jpg. Extension is also stored in the database as the extension was not previously.
> problem: wallet upload error messages are not return to user and uploaded file extension is ignored

- client/normal/currencyDetail/fundamentalMetrics.js
- lib/database/Images.js
- lib/properties.js
- views/templates/normal/currencyDetail/currencyDetail.html
solution: Create a helper to the walletimages collection and display on the currency details page. Currently not styled. I had to create a new global var to assist in displaying the correct image location on the server which is public. Please advise is this approach is not suitable.
> problem: wallet images are not displayed on the currency details page #36

- .meteor/packages
- .meteor/versions
- lib/properties.js
- server/methods/imageUpload.js
solution: watermark uploaded images to enable easy detection of re-used images. GM library used and can be used on other tickets. Sample watermark provided here: https://i.imgur.com/sN6PcN1.png
> problem: users can pull wallet images from site and re-upload #32

- client/normal/currency.css
- views/templates/normal/currencyDetail/features.html
- views/templates/normal/currencyDetail/redflags.html
#257 removes some necessary modals and other functionality, moves the help button to *within* a submit button so there's no way to get help without also submitting the form, and it forces all comments to be full-width which is just weird and silly.
Solution: revert b5f47f1 and edf91f5
> Problem: modals broken, help link broken, full width layout for comments

- client/normal/bounties/bounties.js
Solution: Grey out the 'take bounty' buttons if the user is already working on another bounty to prevent him/her from starting multiple bounties
> Problem: Users can take a new bounty while an existing bounty is running (#275)

- server/serverdb/addCoin.js
Solution: use a case insensitive check instead of a case sensitive check when checking if a currency name already exists. #292
> Problem: currency name check on /addcoin is case sensitive

- imports/api/hashpower/methods.js
- imports/ui/pages/hashpower/allHashpower.js
Solution: Add the 'deleteHashpower' method once again and review the 'canDelete' helper to only allow users to delete their own hash data
> Problem: Users can't delete their own hash power data (#328)

- client/users/ratings/ratings.js
- server/methods/imageUpload.js
Solution: When changing a wallet image the record is deleted in the collection however the file on the server is not deleted. This should happen to preserve file space and integrity in blockrazor. #289
> problem: file not deleted when changing wallet img

- imports/ui/pages/compareCurrencies/compareCurrencies.js
Solution: show wallet values-min proportionate to max-min. I'm not even sure where wallet field is shown. Removed hard-coded values, codebase is {max: 400, min: 400} #194
> Problem: radar chart does not maximise available values

- server/methods/elorankings.js
Solution: Call the 'updateGraphdata' method every time average ELO values are calculated to ensure that graph's upper and lower bounds are correct
> Problem: Radar graph data not normalized (#304)

- client/normal/desktop.js
- client/normal/menu.js
- lib/database/UserData.js
- views/layouts/desktop.html
Solution: Save user preferences by window.width breakpoints aligned with bootstrap breakpoints. Expose screenSize session var. This will only work on desktop layout. The default for opened sidebar is width over 991px. #350
> Problem: sidebar menu closes when reloading page

- imports/test/server/unit/hashpower.test.js
Solution: Add unit tests for hash power data methods
> Problem: Hash power data methods are not tested (#368)

- imports/test/server/unit/validateprop.test.js
solution: no need to read the file each time, just once now
> problem: prop validate test script slow

- imports/ui/pages/currencyDetail/commentRender.html
- imports/ui/pages/currencyDetail/commentRender.js
- imports/ui/pages/currencyDetail/feature.html
- imports/ui/pages/currencyDetail/feature.js
Solution: Rename the `comment` template into `commentRender` to prevent errors, as `comment` is a field in `comments` which causes issues
> Problem: /currency/:slug is catching errors (#471)

- DESCRIPTIVE_C4.MD
The file was attributed twice to Pieter Hintjens. License information, further reading, etc was placed at the start of the text instead of at the end. The start of the file should be exciting to read and get people excited.
solution: put license information and further reading at the end of the file, make the start of the file interesting and qualifying so that people actually read it.
> Problem: redundant attribution, bad layout, incorrect copyright

- imports/ui/pages/returnedCurrencies/currency.html
Solution: Link to the auction page from the icon on the winning currency
> problem: Icon on winning currency does not link to auction page (#531)

- imports/ui/pages/compareCurrencies/compareCurrencies.js
Solution: Replace `pushState` with `replaceState` to prevent browser history spamming and add `path` to `state` to stay compliant with the FlowRouter.
> Problem: Currency comparison page cannot be shared (#530)

- imports/api/miscellaneous/appLogs.js
- imports/api/miscellaneous/server/publications.js
- imports/startup/both/routes.js
- imports/ui/components/sideNav/sideNav.html
- imports/ui/pages/moderator/appLogs/appLogs.js
- imports/ui/pages/moderator/appLogs/appLogs.template.html
Solution: Implement a page at `/applogs` where moderators can easily view application logs and filter them by message or level.
> Problem: No easy way to view applogs collection (#567)

- imports/ui/pages/auctions/currencyAuction.js
Solution: Show 5 decimal places instead of 2 on currency auction page.
> Problem: Not enough digits after decimal place on currency auction page (#532)

- imports/ui/pages/problems/problemImages.html
- imports/ui/pages/problems/problemImages.js
solution: update helpers to exclude . from the jquery lookup. dots on lookup are not supprted #651
> problem:images cannot be expanded

- imports/ui/components/topNav/topNav.html
solution: add responsive css classes to hide and show dom elements based on screensize #626. 
For those interested in how to handle dom manipulation based on screensize. Checkout the following [Bootstrap 4 documentation ](https://getbootstrap.com/docs/4.0/utilities/display/).
> problem:full usernames are too big for small screens

- client/main.css
- imports/ui/pages/currencyDetail/walletimages.html
`solution:` Modal is now responsive being 80% of the width of the page #703
> problem: wallet image modal does not expand to enclose entire image

- imports/ui/pages/problems/problem.html
- imports/ui/pages/problems/problem.js
Solution: Use a non-reactive helper for header and text to prevent text duplication when editing with x-editable.
> Problem: [/problem] text in edited fields gets duplicated when editing (#673)

- imports/ui/pages/compareCurrencies/compareCurrencies.html
- imports/ui/pages/compareCurrencies/compareCurrencies.js
- imports/ui/pages/currencyDetail/currencyInfo.html
- server/API_requests/github.js
Solution: Calculate currency comparison prices (CPC and CPT) when updating values for market cap and circulating coins. Show CPC and CPT on 'currency compare' page and on the 'currency detail' page.
> Problem: No currency comparison prices (#627)

- imports/api/auctions/server/methods.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
Solution: Remove the winning currency when the auction ends and put a new UI element in its place so users can still get to the auction page.
> Problem: Winning currency (auction) not removed when no winner (#704)

- imports/api/coins/server/methods.js
- imports/ui/pages/bounties/bounties.js
Solution: Reset the new currency bounty when a new currency is added, not when it's approved.
> Problem: New currency bounty does not reset until new currency approved (#718)

- server/methods/elorankings.js
Solution: Use github repo validity as a data point when calculating data quality metric.
> Problem: Data quality metric does not check for github repo (#736)

- client/main.js
- imports/api/users/server/publications.js
Solution: In `slugify` helper, instead of slugifying author's name, subscribe to user data and get the slug from the database.
> Problem: Use of slugs as unique id for usernames causes problems when two people have same name (#747)

- client/main.js
- imports/api/wallet/server/methods.js
- imports/ui/pages/transactions/transactions.html
solution: add descriptive transaction type name in the grid, global helper created to reuse code on other pages #748
> problem:no reason shown for transactions

- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
solution: the price attribute was not included in the Find {fields: price:1} section #723
> problem: price not on home page

- imports/ui/components/radarGraph.js
- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
Solution: Sort cryptocurrencies on the front page by data quality rank (of course, featured ones still come first)
> Problem: [/] first coins on / route don't look complete (#780)

- imports/ui/pages/ratings/question.js
solution: import statement for Cookie framework was missing from the js file #819
> problem:answerRating: ReferenceError: Cookies is not defined

- imports/api/coins/currencies.js
- imports/api/problems/problems.js
Solution: Apparently, Mocha doesn't like the new LocalizableCollection, so, fallback to regular Mongo collections if isTest flag is active in order to fix the tests.
> Problem: Travis test is breaking, but production doesn't break (#880)

- imports/api/users/client/users.js
- imports/api/users/methods.js
- imports/ui/layouts/mainLayout/mainLayout.js
Solution: the logic is ironcland, the unload event and meteor.method don't play together. reverted to saving all the time. #565
> Problem: undefered call to set user preference for open/close sidebar

- AUTHORS
- imports/ui/pages/bounties/bounties.js
solution: 
small logic change to continue even when users _id and name not available. this will display hashpower API bounties also to the guests. when a guest trying to start taking a bounty, he/she will be redirected to the login page.
> problem: hashpower API bounties not shown unless logged in. issue #887

- imports/ui/layouts/mainLayout/mainLayout.scss
solution: reduced z-index of modal than the z-index of navbar
(applied for every modal commonly, because some other modals also appeared below navbar)
> problem: [/] warning modal is displayed under navbar #911

- imports/api/users/usersStats.js
Solution: used new Set() to diff if userOnline callback trigger erroneusly, and made observeChanges compare lengths with on memory and database before updating connected field. #882
> Problem: userStats observeChanges triggering on all instances #882

- imports/ui/pages/wallet/walletTransactions.js
solution: sorted transactions while filtering for displaying in the table
> problem: wallet transactions are not sorted by datetime #952

- imports/api/bounties/server/methods.js
- imports/ui/pages/bounties/bounties.js
- imports/ui/pages/bounties/bountyRender.html
Solution: corrected last reward value for add new currency bounty
Note:  previously the bounty completion timestamp is not being saved in the DB. I have corrected it to save the 'completedAt' timestamp in the DB for newly completing bounties.
However as the previously completed bounties not having a completion timestamp, for selecting last bounty, a priority sort is used.
With that, the sorting will be performed first with 'completedAt' field and if there is no such field (for old bounties) the sorting will be performed with 'expiresAt' field.
> Problem: add new currency last reward incorrect #951

- imports/api/communities/methods.js
- imports/api/communities/server/methods.js
- imports/api/wallet/server/methods.js
- imports/ui/pages/communities/communities.js
- imports/ui/pages/moderator/moderatorDash/approveCommunityImage.js
- imports/ui/pages/moderator/moderatorDash/approveWalletImage.js
- server/methods/elorankings.js
Solution: Implement a way for moderators to reject invalid wallet and community images, and purge user's credit and ELO rankings associated with that particular image. Also, don't process community and wallet ELO rankings before images are approved to prevent incorrect ELO scores.
> Problem: Community and wallet rating questions cannot be rejected by moderators (#961)

- imports/api/utilities.js
- imports/ui/pages/problems/problems.js
Solution: changed [/problems] route as it also queries db on every keystroke, but keeping [/problems/:id] as is. #873
> Problem: no encapsulation for initializing local collection #873

- imports/api/auctions/server/methods.js
- imports/ui/layouts/mainLayout/mainLayout.html
- imports/ui/pages/auctions/currencyAuction.js
- imports/ui/pages/auctions/currencyAuction.template.html
solution: modified to use KZR as bid payment method for any currency
Note: The symbol of Krazor is saved as ZKR rather than KZR in the database. (in the currencies collection)
It need to be modified, however a translator used to translate 'ZKR' to 'KZR' until db getting updated.
> problem: [/currencyauction] insufficient funds #1036

- .meteor/packages
- .meteor/versions
- imports/startup/both/routes.js
Solution: Use subs-manager within templates and router, or delete template subscriptions which would be an anti-pattern. I intend to set a generic timer of a minute for cache (subscription still running) termination. #333
> Problem: duplicate subscription calls + navigation speed

- imports/api/auctions/server/methods.js
- imports/ui/pages/auctions/currencyAuction.js
- imports/ui/pages/auctions/currencyAuction.template.html
Solution: Make auction changes reactive again, so the timer doesn't suddenly stop, and invoke the `placeBid` method with correct parameters again (`options.currency` is the currency `_id`, not the currency symbol) to fix the problem with featured currencies not showing on the home route.
> Problem: Auctions seem to stop counting down after a while (#1045)

- imports/ui/pages/bounties/bounties.js
- imports/ui/pages/bounties/bountyRender.js
Solution: In bounties.js split away calculateReward to operate on LocalBounties local collection with this.ids.get() filter, and adjust bounties helper query to sort by calculatedReward value of document. Ideally calculateReward would be set to 0 in fields projection in helper that renders the list in bounty.js so that list doesn't rerender unless the sort order changes, and bountyRender having a separate helper that queries for that field to show it in that template. #791
> Problem: calculateReward in [/bounties] runs a lot and everywhere

- imports/api/users/methods.js
- imports/ui/layouts/mainLayout/mainLayout.js
Solution: Publications didn't work. Wind up using unload event in meteor.startup writing short function as callback since it appears the function didn't manage to finish running before. #989
> Problem: sidebar preference updates always write to DB

- client/main.js
- imports/api/problems/methods.js
- imports/api/problems/problems.js
- imports/api/utilities.js
- imports/ui/pages/problems/problems.js
Solution: made the reactive function the hard way tapping into reactive queries, and killing the tap once original query stopped. #993
> Problem: Localizable Collection should tap live queries to update local

- imports/api/utilities.js
Solution: Check whether result is defined in LocalizableCollection's `findOne` method in order to fix the issue.
> Problem: Clicking logo does not direct to home route (#1105)

- imports/ui/pages/returnedCurrencies/returnedCurrencies.js
Solution: Query the local `Currencies` collection instead of the global one to determine whether to show the 'put your coin here' item.
> Problem: Winning currency displayed at same time as "put your coin here" item (#1164)

- imports/ui/pages/auctions/allAuctions.js
- imports/ui/pages/auctions/allAuctions.template.html
Solution: Use momentjs to replace the absolute time with descriptive time (e.g. 'ends in 3 hours'). Use 'ends' for opened auctions and 'ended' for closed.
> Problem: Time displayed on auctions is absolute (#1151)

- imports/api/hashing/methods.js
Solution: Fix the regex used to find the currency in `hashrateApi` method in order to prevent incorrect matches. (Ethereum Classic was sometimes matched instead of Ethereum)
> Problem: Invalid hashpower calculations for Ethereum Classic (#1215)

- imports/api/activityLog/activityIPs.js
- imports/api/activityLog/methods.js
- imports/api/activityLog/server/publications.js
- imports/api/indexDB.js
- imports/api/users/methods.js
- imports/api/users/server/publications.js
- imports/api/wallet/server/publications.js
- imports/startup/both/routes.js
- imports/ui/components/sideNav/sideNav.html
- imports/ui/components/topNav/topNav.html
- imports/ui/pages/moderator/flaggedUsers/flaggedIP.html
- imports/ui/pages/moderator/flaggedUsers/flaggedIP.js
- imports/ui/pages/moderator/flaggedUsers/flaggedUsers.html
- imports/ui/pages/moderator/flaggedUsers/flaggedUsers.js
- imports/ui/pages/suspended/suspended.js
Solution: Implement a new view where moderators can see all users that share an IP address (whether on signup, login or general access) and let moderators decide to either ban all duplicate accounts or to ignore the specific IP address for a month.
> Problem: Can't easily ban duplicate accounts (#1216)

- imports/ui/components/typeahead.js
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: Moving the `id` property out of the `data` scope fixes the issue. It also fixes the issue with highlight not defined in #1295.
> Problem: Typeahead can't handle external changes well (#1248, #1295)

- imports/ui/pages/currencyDetail/fundamentalMetrics.js
Solution: Add `chart.js` options that should force the correct aspect ratio and prevent deformations.
> Problem: Distribution graph is deformed on small screens (#1302)

- imports/api/problems/methods.js
- imports/startup/both/routes.js
- imports/ui/components/sideNav/sideNav.html
- imports/ui/pages/suspended/suspended.html
Solution: Let suspended users access questions/problems, put a link to questions/problems on the suspended page, and hide other side bar links when the user is suspended.
> Problem: Suspended users cannot view and post problems/questions (#1333)

- imports/api/payments/server/startup.js
Solution: Use the value of environmental variable `NODE_TYPE` to determine whether to run a certain syncedcron job. An example how to use this is commented in `/imports/payments/server/startup.js`.
> Problem: Cannot specify instances for syncedcron jobs to run on (#1334)

- imports/api/coins/server/publications.js
- imports/ui/pages/bounties/bounties.js
Solution: Use only currencies that user `Proof of Work` as consensus security when generating hashpower API bounties.
> Problem: Hashpower API bounties are created for PoS currencies (#1323)

- imports/api/payments/server/methods.js
Solution: Allow multiple transaction hashes in the same `bulkPayments` call and calculate the total amount by grouping all transactions with the same hash.
> Problem: Users cannot deposit Monero into their wallet (#1313)

- AUTHORS
- imports/ui/pages/moderator/moderatorDash/moderatorPendingCurrency.html
Problem : When moderator goes to currency approval page he can't see image of newly added currency.
Solution : 
Replaced `currencyReview.currencyName.currencyLogoFilename` with `currencyReview.currencyLogoFilename`
Wrong file name reference was being called.
> #1322 Fixed issue of currency image not showing up in moderator currency approval page

- imports/ui/pages/auctions/currencyAuction.js
Solution: Reverted part of previous solution, that *tried* adding a check within typeahead in a wrong place, too. Why when something happens with my self-contained/encapsulated code involved they must go an mess or spend hours reading it without reading documentation I don't know.
Added a check within an actual form, that will submit on enter and so I'm disabling enter event listener for typeahead.
> Problem: problem: [currencyAuction] able to place with no currency

- imports/ui/pages/currencyDetail/fundamentalMetrics.js
- imports/ui/pages/returnedCurrencies/currency.js
Disables chart animations on `/` & `/currency/:x`
Solves: #1395
> Problem: 1395 Disables chart animation on / & currency/:x

- imports/startup/both/routes.js
Solution : use FlowRouter.route('*', { /*...*/ }) instead!
> #1407 Problem: Flow.router deprecated warning in browser console log

- client/main.js
Solution: Check if the object `doc` is defined in `hasUserVoted` global helper before trying to access its properties and update collection references when collections are dynamically imported in `/client/main` in order to fix `hasUserVoted` functionality.
> Problem: [currency/x] Cannot read property 'downVoted' of undefined (#1435)

- .meteor/packages
- .meteor/versions
- client/main.js
- imports/ui/components/compatability/moment.js
- imports/ui/components/topNav/topNav.js
- imports/ui/layouts/mainLayout/mainLayout.js
- imports/ui/pages/addCoin/addCoin.js
- imports/ui/pages/bounties/bounties.js
- imports/ui/pages/codebase/codebase.js
- imports/ui/pages/communities/commQuestions.js
- imports/ui/pages/communities/communities.js
- imports/ui/pages/currencyDetail/currencyInfo.js
- imports/ui/pages/editProfile/editProfile.js
- imports/ui/pages/moderator/moderatorDash/approveCommunityImage.js
- imports/ui/pages/moderator/moderatorDash/approveWalletImage.js
- imports/ui/pages/moderator/moderatorDash/moderatorPendingCurrency.js
- imports/ui/pages/problems/problem.js
- imports/ui/pages/ratings/currencyChoices.js
- imports/ui/pages/ratings/question.js
- imports/ui/pages/ratings/ratings.js
- package-lock.json
- package.json
Solution: Remove Meteor `momentjs:moment` package and replace it with dynamically imported `moment` npm package. Stub `moment` before the package is loaded in order to prevent inconsistent behavior. Remove `sweetalert2` Meteor package, and use dynamically imported `sweetalert2` npm package sitewide. Update existing `sweetalert` npm package to `sweetalert2`. Upgrade the existing `sweetalert` code to `sweetalert2` API.
> Problem: reactive-table, moment, sweetalert2 are not dynamically imported (#1438)

- imports/startup/client/index.js
- imports/ui/pages/theme.html
- package-lock.json
Solution: Dynamically import `bootstrap` to prevent eager importing of `popper.js`. Dynamically importing `bootstrap` also has performance benefits.
> Problem: popper.js is in the bundle (20kb) (#1439)

- imports/api/exchanges/exchanges.js
- imports/api/exchanges/methods.js
- imports/api/exchanges/server/publications.js
- imports/startup/both/routes.js
- imports/ui/components/sideNav/sideNav.html
- imports/ui/pages/exchanges/exchanges.js
- imports/ui/pages/moderator/exchanges/removeExchanges.html
- imports/ui/pages/moderator/exchanges/removeExchanges.js
Solution: Change the behavior of the remove button on `/exchanges` page. Now, instead of deleting the exchange, it proposes the removal, and moderators have to either approve or deny the removal. Add a new page where moderators can do exactly that.
> Problem: Exchanges can be removed without moderation (#1448)

- imports/ui/pages/bounties/bounties.scss
Solution: Change the top margin for js-shareurl to -20px from -35px
> Problem: overlapping share button with header on /bounties #1466

- client/main.js
Solution: one line fix as custom file imported and used in the client/main.js as moment, while actual moment.js added as a global variable. Therefore, for other files it is fine as the `moment` refers to global window.moment. But in client/main.js, the `moment` refers to the imported custom file from client/compatibility (which seems not fully implemented yet, dunno though).
> Problem: [/currency/x] created times not showing #1511

- docs/TESTING.md
Solution: Add client side testing documentation to `docs/TESTING.md`.
> Problem: Testing docs aren't on exhibit (#1526)

- .travis.yml
- imports/api/coins/methods.js
- imports/ui/components/typeahead.ui-test.js
Solution: Fix two failing test cases in the existing test. The first one has been fixed by commenting out an unnecessary step, and the second one has been fixed by fixing the `listChild` method, as it was returning invalid results in some edge cases. Add a new method for generating test data as CI environment runs with an empty database, and call that method in the test initialization.
> Problem: Typeahead untested (#1529)

- imports/startup/client/index.js
- imports/startup/client/testingCollectionGlobals.js
Solution: Import all collections dynamically and proxy global collection calls on production to prevent their global usage when in production.
> Problem: Collections in global scope may only be used in development (#1527)

- imports/ui/pages/addCoin/addCoin.js
solution: validate genesis timestamp only if BTCfork not checked
> problem: [/addCoin] incorrect validation when BTCfork checked #1546

- imports/api/exchanges/methods.js
- imports/ui/pages/addCoin/addCoin.js
Solution: When user creates an exchange on `/addCoin`, automatically add that exchange to the list of selected exchanges for the coin that's being created.
> Problem: Newly created exchanges are not selected on /addCoin (#1567)

- imports/ui/pages/returnedCurrencies/returnedCurrencies.html
Solution: `scrollmagic` requires an element with `loader` id at all times, so don't remove the empty `loader` element even if there are no more results.
> Problem: Type error while scrolling down in home (#1550)

- imports/startup/client/testingCollectionGlobals.js
- imports/ui/components/typeahead.ui-test.js
Solution: Prefix globally exposed collections with `testing` and throw an error if these are used in production.
> Problem: Global collections may be only used in development (#1527)

- imports/api/users/methods.js
- imports/api/users/server/publications.js
- imports/ui/pages/editProfile/editProfile.html
- imports/ui/pages/editProfile/editProfile.js
Solution: Allow users to pass two-factor authentication with predefined backup 2FA tokens. Each of the predefined backup 2FA tokens can be used only once, as it's reset when used. Show 2FA backup tokens on the `editProfile` page so user can save them/write them down. Also, allow users to regenerate all backup 2FA tokens if they believe they may have been compromised.
> Problem: 2FA doesn't have backup codes (#1605)

- imports/ui/components/typeahead.ui-test.js
Solution: Test if the default empty message is rendered correctly.
> Problem: Typeahead custom empty messages are untested (#1585)

- imports/api/wallet/methods.js
Solution: passing the wallet creator id instead of current logged in user id to the removeUserCredit function
> Problem: wrong kzr wallet notifications #1636

- imports/ui/pages/moderator/appLogs/appLogs.html
- imports/ui/pages/moderator/appLogs/appLogs.js
Solution: hiding the 'more data' btn when there are no results to display
> Problem: 'more data' displayed without data #1642

- imports/api/users/server/startup.js
Solution: Remove observer logic and check directly if the counter should be increased/decreased when adding/removing users from `UsersStats`'s `connected` field.
> Problem: [/] Users online is always 0 (#1651)

- imports/ui/layouts/blockrazor.scss
solution: add a blockrazor scss file to extend bootstrap and bootswatch when needed #1535
> problem: no way to extend bootswatch lux

- imports/ui/pages/moderator/problems/solvedProblems.html
Solution: Display "No problems available" if there are no solved problems.
> Problem: Missing helper text on /solved-problems (#1703)

- imports/ui/shared/sidebar/sidebar.js
Solution: removed inappropriate `preventDefault()` call, which caused all moderator menu items unclickable
> Problem: Moderator menu items not working #1719

- imports/ui/pages/userProfile/userProfile.html
Solution: Left align all text on all tabs in `/profile` page.
> Problem: Misaligned text in /profile page (#1758)

- imports/ui/shared/sidebar/sidebar.html
- imports/ui/shared/sidebar/sidebar.js
Solution: Corrected the style issue in `get help` navigation item, which is caused due to nested links (clicking on navigation item should redirect to [/problems] page while, clicking on notification badge on top of it should redirect to [/notifications] page)  and added css classes to unstyled navigation items
> Problem: Some links in the sidebar mis-styled #1770

- imports/ui/layouts/layout.scss
Solution: Add transition property to the icons with ease-in-out.
> Problem: Rough Transitions on Homepage Icons #1814

- imports/ui/shared/sidebar/sidebar.js
solution: add logic when clicking buttons to check if its a parent menu item, if it is do not close the menu #1891
> problem: side bar closing on mobile for dropdowns

- client/main.css
solution: add padding to the alert to ensure its bottom margin is higher than the header height #1903
> problem: notifications bubble is hidden under header

- imports/ui/pages/landingpage/landingpage.js
solution: show the side menu again when you leave the landing page even if you are authenticated #1944
> Problem: not everyone notices that theres a side menu on large screens

- server/kadira.js
Solution: Add SSL support for Kadira engine at domain `kadira.emurgolance.org` and change connection parameters to make sure HTTPS is being used on the client.
> Problem: Kadira requests are being blocked (#1887)

- i18n/currency.en.i18n.json
- imports/api/coins/currencies.js
- imports/api/coins/methods.js
- imports/api/coins/server/startup.js
- imports/startup/server/index.js
- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: Use the GitHub search API to populate a collection with relevant related repos for each currency. Take care of GitHub's rate limiting with appropriate pauses. Show fetched data in a new tab on the currency detail page.
> Problem: Related github repos not considered (#1972)

- imports/api/activityLog/methods.js
- imports/startup/server/fixtures.js
- imports/ui/pages/moderator/flaggedUsers/flaggedUsers.js
Solution: Modify the current ignore IP mechanism and add a `whitelist` flag to ignored IPs list to denote a whitelisted IP which has no expiry time. Add a fixture to add 127.0.0.1 to the list if it's not already there. Check this list for addresses before using them.
> Problem: No IP whitelist for banning system (#1978)

- i18n/currency.en.i18n.json
- imports/api/coins/currencies.js
- imports/api/coins/methods.js
- imports/api/coins/server/startup.js
- imports/ui/pages/currencyDetail/currencyInfo.html
- imports/ui/pages/currencyDetail/currencyInfo.js
Solution: Add a summary on the currency details page that includes: related projects on Github, watchers on all projects, likes on all projects, watchers per project and top 5 languages. Stats are updated daily with a cron job.
> Problem: There's no summary of github projects for currencies (#1988)

- imports/ui/pages/moderator/flaggedUsers/flaggedUsers.js
Solution: Make sure that sorting works even when some data is not available.
> Problem: Can't sort suspicious IP's by IP login time (#1983)

- imports/api/coins/methods.js
Solution: Since there's no `subscribers_count` field in the GitHub Search API v3, use the preview Search API v3 and use the `watchers` field which should be the same thing.
> Problem: Total GitHub watchers and likers are the same number (#2013)
